#!/usr/bin/env node

import {execFileSync} from 'node:child_process';
import {copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync} from 'node:fs';
import {dirname, join, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const REMOTION_ROOT = join(ROOT, 'remotion');
const COURSE_ROOT = join(ROOT, 'git-course/episodes');
const FPS = 30;
const EPISODES = [
  ['ep01-what-git-stores', 'GitCourseEp01WhatGitStores', 'EP01'],
  ['ep02-working-tree-index-repo', 'GitCourseEp02WorkingTreeIndexRepo', 'EP02'],
  ['ep03-commit-snapshot', 'GitCourseEp03CommitSnapshot', 'EP03'],
  ['ep04-branch-is-pointer', 'GitCourseEp04BranchIsPointer', 'EP04'],
  ['ep05-head', 'GitCourseEp05Head', 'EP05'],
  ['ep06-merge', 'GitCourseEp06Merge', 'EP06'],
  ['ep07-rebase', 'GitCourseEp07Rebase', 'EP07'],
  ['ep08-reset-revert-restore', 'GitCourseEp08ResetRevertRestore', 'EP08'],
];

const fail = (message) => {
  throw new Error(message);
};

const loadEpisode = ([id, composition, symbol]) => {
  const path = join(COURSE_ROOT, `${id}.json`);
  const data = JSON.parse(readFileSync(path, 'utf8'));
  data.episodeId === id || fail(`${path}: episodeId must be ${id}`);
  Array.isArray(data.scenes) && data.scenes.length > 0 || fail(`${path}: scenes must not be empty`);
  let cursor = 0;
  const ids = new Set();
  for (const scene of data.scenes) {
    typeof scene.id === 'string' && scene.id.length > 0 || fail(`${path}: scene id is required`);
    !ids.has(scene.id) || fail(`${path}: duplicate scene id ${scene.id}`);
    ids.add(scene.id);
    Number.isFinite(scene.start) && Number.isFinite(scene.duration) && scene.duration > 0 || fail(`${path}: invalid timing for ${scene.id}`);
    scene.start === cursor || fail(`${path}: ${scene.id} starts at ${scene.start}, expected ${cursor}`);
    cursor += scene.duration;
  }
  cursor === data.durationSeconds || fail(`${path}: scenes end at ${cursor}, durationSeconds is ${data.durationSeconds}`);
  data.durationSeconds >= 180 && data.durationSeconds <= 300 || fail(`${path}: duration must be 3–5 minutes`);
  return {id, composition, symbol, ...data};
};

const validateNarration = (episode) => {
  let previousStart = -1;
  const ids = new Set();
  episode.scenes.forEach((scene, index) => {
    const {segmentId, voiceStart: start, text} = scene.narration ?? {};
    Number.isFinite(start) || fail(`${episode.id}:${scene.id}: narration.voiceStart must be a number`);
    typeof text === 'string' && text.trim().length > 0 || fail(`${episode.id}:${scene.id}: narration.text is required`);
    !ids.has(segmentId) || fail(`${episode.id}:${scene.id}: duplicate segment id ${segmentId}`);
    ids.add(segmentId);
    const end = scene.start + scene.duration;
    start >= scene.start - 0.5 && start < end || fail(`${episode.id}:${scene.id}: voice start is outside its scene transition tolerance`);
    start > previousStart || fail(`${episode.id}:${scene.id}: narration must be ordered`);
    previousStart = start;
  });
};

const timelineSource = (episodes) => {
  const blocks = episodes.map((episode) => {
    const scenes = episode.scenes.map(({id, title, duration}) => `  {id: ${JSON.stringify(id)}, title: ${JSON.stringify(title)}, duration: seconds(${duration})},`).join('\n');
    return `export const ${episode.symbol}_SCENES = [\n${scenes}\n] as const;\nexport const ${episode.symbol}_DURATION_IN_FRAMES = ${episode.symbol}_SCENES.reduce((sum, scene) => sum + scene.duration, 0);`;
  });
  return `// Generated by scripts/git-course.mjs from git-course/episodes/*.json.\n// Do not edit by hand.\nimport {seconds} from '../timeline';\n\n${blocks.join('\n\n')}\n`;
};

const generateTimelines = (episodes) => {
  const target = join(REMOTION_ROOT, 'src/videos/git-course/data/episodeTimelines.generated.ts');
  writeFileSync(target, timelineSource(episodes));
};

const generateRanges = (episode, sceneId) => {
  const selected = sceneId ? episode.scenes.filter((scene) => scene.id === sceneId) : episode.scenes;
  selected.length > 0 || fail(`${episode.id}: unknown scene ${sceneId}`);
  const dir = join(REMOTION_ROOT, 'renders/git-course', episode.id, 'tmp/generated-ranges');
  mkdirSync(dir, {recursive: true});
  const path = join(dir, `${sceneId ?? 'scenes'}.tsv`);
  writeFileSync(path, selected.map((scene) => `${String(episode.scenes.indexOf(scene) + 1).padStart(2, '0')}_${scene.id.replaceAll('-', '_')}\t${scene.start * FPS}\t${(scene.start + scene.duration) * FPS - 1}`).join('\n') + '\n');
  return path;
};

const generateNarrationSource = (episode) => {
  const dir = join(REMOTION_ROOT, 'renders/git-course', episode.id, 'tmp/narration-source');
  mkdirSync(dir, {recursive: true});
  const rows = ['# segment_id\tvoice_start_seconds\tscene_end_seconds'];
  for (const scene of episode.scenes) {
    const {segmentId, voiceStart, text} = scene.narration;
    writeFileSync(join(dir, `${segmentId}.txt`), `${text.trimEnd()}\n`);
    rows.push(`${segmentId}\t${voiceStart}\t${scene.start + scene.duration}`);
  }
  writeFileSync(join(dir, 'manifest.tsv'), `${rows.join('\n')}\n`);
  if (episode.content?.alignmentMarkdown) {
    writeFileSync(join(dir, 'alignment.md'), episode.content.alignmentMarkdown);
  }
  return join(dir, 'manifest.tsv');
};

const generateReleaseSource = (episode) => {
  if (!episode.release?.bilibiliMarkdown) return null;
  const dir = join(REMOTION_ROOT, 'renders/git-course', episode.id, 'current/release');
  mkdirSync(dir, {recursive: true});
  const path = join(dir, 'bilibili.md');
  writeFileSync(path, episode.release.bilibiliMarkdown);
  return path;
};

const validate = ({checkGenerated = true} = {}) => {
  const episodes = EPISODES.map(loadEpisode);
  episodes.forEach(validateNarration);
  const generated = join(REMOTION_ROOT, 'src/videos/git-course/data/episodeTimelines.generated.ts');
  if (checkGenerated && existsSync(generated)) {
    readFileSync(generated, 'utf8') === timelineSource(episodes) || fail(`${generated}: stale; run pnpm git-course:generate`);
  }
  return episodes;
};

const command = process.argv[2] ?? 'validate';
const episodeId = process.argv[3];
const sceneIndex = process.argv.indexOf('--scene');
const sceneId = sceneIndex >= 0 ? process.argv[sceneIndex + 1] : null;
const episodes = validate({checkGenerated: command !== 'generate'});

if (command === 'validate') {
  console.log(`Validated ${episodes.length} episode JSON files and narration timelines.`);
} else if (command === 'generate') {
  generateTimelines(episodes);
  episodes.forEach(generateReleaseSource);
  console.log('Generated Remotion timelines from episode JSON files.');
} else if (command === 'narration') {
  const episode = episodes.find((item) => item.id === episodeId) ?? fail(`Unknown episode: ${episodeId}`);
  console.log(generateNarrationSource(episode));
} else if (command === 'release') {
  const episode = episodes.find((item) => item.id === episodeId) ?? fail(`Unknown episode: ${episodeId}`);
  console.log(generateReleaseSource(episode) ?? `${episode.id}: no release source`);
} else if (command === 'render') {
  const episode = episodes.find((item) => item.id === episodeId) ?? fail(`Unknown episode: ${episodeId}`);
  generateTimelines(episodes);
  const ranges = generateRanges(episode, sceneId);
  const current = join(REMOTION_ROOT, 'renders/git-course', episode.id, 'current');
  const sceneRunDir = sceneId ? join(REMOTION_ROOT, 'renders/git-course', episode.id, 'tmp/scenes', sceneId) : null;
  const env = {
    ...process.env,
    RANGES_FILE: ranges,
    OUT_ROOT: join(REMOTION_ROOT, 'renders/git-course', episode.id, 'tmp/chunks'),
    FINAL_PATH: join(current, `${episode.id}.mp4`),
    ...(sceneRunDir ? {RUN_DIR: sceneRunDir, CLEAN_RUN_DIR: '1', SKIP_CONCAT: '1', AUDIT_SEGMENTS: '1'} : {}),
  };
  execFileSync(join(REMOTION_ROOT, 'scripts/render-ranges.sh'), [episode.composition, episode.id, String(episode.durationSeconds * FPS), '600'], {cwd: REMOTION_ROOT, env, stdio: 'inherit'});
  if (sceneRunDir) {
    const rendered = readdirSync(join(sceneRunDir, 'segments')).filter((name) => name.endsWith('.mp4'));
    rendered.length === 1 || fail(`${sceneRunDir}: expected one rendered scene, found ${rendered.length}`);
    const scene = episode.scenes.find((item) => item.id === sceneId);
    const name = `${String(episode.scenes.indexOf(scene) + 1).padStart(2, '0')}_${scene.id.replaceAll('-', '_')}.mp4`;
    const sceneDir = join(current, 'scenes');
    mkdirSync(sceneDir, {recursive: true});
    copyFileSync(join(sceneRunDir, 'segments', rendered[0]), join(sceneDir, name));
    console.log(`Current scene: ${join(sceneDir, name)}`);
  }
} else {
  fail(`Usage: git-course.mjs validate|generate|narration|release|render <episode-id> [--scene <scene-id>]`);
}
