import type {VideoRegistration} from '../types';
import {
  COMPONENT_LAB_DURATION,
  COMPONENT_LAB_SCENE_DURATION,
  ComponentLab,
  ComponentLabCaptions,
  ComponentLabGraph,
  ComponentLabLayout,
  ComponentLabState,
  ComponentLabStress,
  ComponentLabTerminal,
} from './ComponentLab';
import {
  EP01_DURATION_IN_FRAMES,
  EP01_SCENES,
  Ep01BadModelPreview,
  Ep01IntegrityPreview,
  Ep01LocalHistoryPreview,
  Ep01PracticeCheckPreview,
  Ep01SnapshotModelPreview,
  Ep01TakeawayPreview,
  Ep01VersionControlPreview,
  Ep01WhatGitStores,
  Ep01WhatGitStoresHook,
} from './episodes/Ep01WhatGitStores';
import {EP02_DURATION_IN_FRAMES, Ep02WorkingTreeIndexRepo} from './episodes/Ep02WorkingTreeIndexRepo';
import {EP03_DURATION_IN_FRAMES, Ep03CommitSnapshot} from './episodes/Ep03CommitSnapshot';
import {EP04_DURATION_IN_FRAMES, Ep04BranchIsPointer} from './episodes/Ep04BranchIsPointer';
import {EP05_DURATION_IN_FRAMES, Ep05Head} from './episodes/Ep05Head';
import {EP06_DURATION_IN_FRAMES, Ep06Merge} from './episodes/Ep06Merge';
import {EP07_DURATION_IN_FRAMES, Ep07Rebase} from './episodes/Ep07Rebase';
import {EP08_DURATION_IN_FRAMES, Ep08ResetRevertRestore} from './episodes/Ep08ResetRevertRestore';
import {EP09_DURATION_IN_FRAMES, Ep09DiffComparesStates} from './episodes/Ep09DiffComparesStates';
import {RefLightboxIntro, RefLightboxOutro} from './kit';
import {FPS, HEIGHT, seconds, WIDTH} from './timeline';

export const registration: VideoRegistration = {
  slug: 'git-course',
  compositions: [
    {
      id: 'GitCourseVisibleSystemIntro',
      component: RefLightboxIntro,
      durationInFrames: seconds(7),
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseVisibleSystemOutro',
      component: RefLightboxOutro,
      durationInFrames: seconds(6),
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseEp01WhatGitStoresHook',
      component: Ep01WhatGitStoresHook,
      durationInFrames: EP01_SCENES[0].duration,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseEp01BadModel',
      component: Ep01BadModelPreview,
      durationInFrames: EP01_SCENES[1].duration,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseEp01VersionControl',
      component: Ep01VersionControlPreview,
      durationInFrames: EP01_SCENES[2].duration,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseEp01SnapshotModel',
      component: Ep01SnapshotModelPreview,
      durationInFrames: EP01_SCENES[3].duration,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseEp01PracticeCheck',
      component: Ep01PracticeCheckPreview,
      durationInFrames: EP01_SCENES[4].duration,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseEp01LocalHistory',
      component: Ep01LocalHistoryPreview,
      durationInFrames: EP01_SCENES[5].duration,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseEp01Integrity',
      component: Ep01IntegrityPreview,
      durationInFrames: EP01_SCENES[6].duration,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseEp01Takeaway',
      component: Ep01TakeawayPreview,
      durationInFrames: EP01_SCENES[7].duration,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseEp01WhatGitStores',
      component: Ep01WhatGitStores,
      durationInFrames: EP01_DURATION_IN_FRAMES,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseEp02WorkingTreeIndexRepo',
      component: Ep02WorkingTreeIndexRepo,
      durationInFrames: EP02_DURATION_IN_FRAMES,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseEp03CommitSnapshot',
      component: Ep03CommitSnapshot,
      durationInFrames: EP03_DURATION_IN_FRAMES,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseEp04BranchIsPointer',
      component: Ep04BranchIsPointer,
      durationInFrames: EP04_DURATION_IN_FRAMES,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseEp05Head',
      component: Ep05Head,
      durationInFrames: EP05_DURATION_IN_FRAMES,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseEp06Merge',
      component: Ep06Merge,
      durationInFrames: EP06_DURATION_IN_FRAMES,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseEp07Rebase',
      component: Ep07Rebase,
      durationInFrames: EP07_DURATION_IN_FRAMES,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseEp08ResetRevertRestore',
      component: Ep08ResetRevertRestore,
      durationInFrames: EP08_DURATION_IN_FRAMES,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseEp09DiffComparesStates',
      component: Ep09DiffComparesStates,
      durationInFrames: EP09_DURATION_IN_FRAMES,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseComponentLab',
      component: ComponentLab,
      durationInFrames: COMPONENT_LAB_DURATION,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseComponentLabLayout',
      component: ComponentLabLayout,
      durationInFrames: COMPONENT_LAB_SCENE_DURATION,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseComponentLabGraph',
      component: ComponentLabGraph,
      durationInFrames: COMPONENT_LAB_SCENE_DURATION,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseComponentLabState',
      component: ComponentLabState,
      durationInFrames: COMPONENT_LAB_SCENE_DURATION,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseComponentLabTerminal',
      component: ComponentLabTerminal,
      durationInFrames: COMPONENT_LAB_SCENE_DURATION,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseComponentLabCaptions',
      component: ComponentLabCaptions,
      durationInFrames: COMPONENT_LAB_SCENE_DURATION,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
    {
      id: 'GitCourseComponentLabStress',
      component: ComponentLabStress,
      durationInFrames: COMPONENT_LAB_SCENE_DURATION,
      fps: FPS,
      width: WIDTH,
      height: HEIGHT,
    },
  ],
};
