#!/usr/bin/env bash
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_lib.sh"

ep41_add_submodule() { cd "$TERMINAL_RECORDING_WORKDIR/parent"; begin_terminal; type_command 'git submodule add ../child.git libs/core'; git -c protocol.file.allow=always submodule add -q ../child.git libs/core; type_command 'git status --short'; semantic_status; type_command 'cat .gitmodules'; cat .gitmodules; finish_terminal; }
ep41_gitlink_entry() { cd "$TERMINAL_RECORDING_WORKDIR/parent"; begin_terminal; type_command 'git ls-files --stage libs/core'; git ls-files --stage libs/core; type_command 'git ls-tree HEAD libs/core'; git ls-tree HEAD libs/core; type_command 'git -C libs/core rev-parse HEAD'; git -C libs/core rev-parse HEAD; finish_terminal; }
ep41_independent_history() { cd "$TERMINAL_RECORDING_WORKDIR/parent"; begin_terminal; type_command 'git log --oneline --decorate -2'; git log --oneline --decorate -2; type_command 'git -C libs/core log --oneline --decorate -2'; git -C libs/core log --oneline --decorate -2; printf 'two independent commit histories\n'; finish_terminal; }

ep42_empty_after_clone() { cd "$TERMINAL_RECORDING_WORKDIR"; begin_terminal; type_command 'git clone parent.git client'; git clone -q parent.git client; type_command 'git -C client submodule status'; git -C client submodule status; type_command 'find client/libs/core -maxdepth 1 -type f'; find client/libs/core -maxdepth 1 -type f; finish_terminal; }
ep42_init_update() { cd "$TERMINAL_RECORDING_WORKDIR"; git clone -q parent.git client; begin_terminal; type_command 'git -C client submodule update --init'; git -C client -c protocol.file.allow=always submodule update --init -q; type_command 'git -C client/libs/core symbolic-ref -q HEAD || echo DETACHED'; git -C client/libs/core symbolic-ref -q HEAD || echo DETACHED; type_command 'git -C client/libs/core rev-parse HEAD'; git -C client/libs/core rev-parse HEAD; finish_terminal; }
ep42_recursive_clone() { cd "$TERMINAL_RECORDING_WORKDIR"; begin_terminal; type_command 'git clone --recurse-submodules parent.git ready'; git -c protocol.file.allow=always clone -q --recurse-submodules parent.git ready; type_command 'git -C ready submodule status'; git -C ready submodule status; type_command 'git -C ready ls-tree HEAD libs/core'; git -C ready ls-tree HEAD libs/core; type_command 'git -C ready/libs/core rev-parse HEAD'; git -C ready/libs/core rev-parse HEAD; finish_terminal; }

ep43_gitlink_change() { cd "$TERMINAL_RECORDING_WORKDIR/developer"; begin_terminal; type_command 'git status --short'; semantic_status; type_command 'git diff --cached --submodule=short'; git diff --cached --submodule=short; type_command 'git -C libs/core log -1 --oneline'; git -C libs/core log -1 --oneline; finish_terminal; }
ep43_missing_child() { cd "$TERMINAL_RECORDING_WORKDIR/developer"; begin_terminal; type_command 'git push origin main'; git push -q origin main; cd ..; type_command 'git clone parent.git consumer'; git clone -q parent.git consumer; type_command 'git -C consumer submodule update --init'; if git -C consumer -c protocol.file.allow=always submodule update --init 2>&1 | tail -4; then :; else true; fi; printf 'child commit is not available\n'; finish_terminal; }
ep43_publish_order() { cd "$TERMINAL_RECORDING_WORKDIR/developer"; begin_terminal; type_command 'git push --recurse-submodules=check origin main'; if git push --recurse-submodules=check origin main 2>&1 | tail -5; then :; else true; fi; type_command 'git -C libs/core push origin feature'; git -C libs/core push -q origin feature; type_command 'git push --recurse-submodules=check origin main'; git push -q --recurse-submodules=check origin main; printf 'parent and child are both available\n'; finish_terminal; }

ep44_add_hotfix() { cd "$TERMINAL_RECORDING_WORKDIR"; begin_terminal; type_command 'git -C repo status --short'; git -C repo status --short; type_command 'git -C repo worktree add -b hotfix ../hotfix main'; git -C repo worktree add -q -b hotfix ../hotfix main; type_command "git -C repo worktree list --porcelain | grep -E '^(HEAD|branch)'"; git -C repo worktree list --porcelain | grep -E '^(HEAD|branch)'; finish_terminal; }
ep44_shared_state() { cd "$TERMINAL_RECORDING_WORKDIR"; begin_terminal; printf 'fixed\n' > hotfix/fix.txt; type_command 'git -C hotfix add fix.txt'; git -C hotfix add fix.txt; type_command 'git -C hotfix commit -m "H1 hotfix"'; git -C hotfix commit -q -m 'H1 hotfix'; type_command 'git -C repo log --all --oneline --decorate -3'; git -C repo log --all --oneline --decorate -3; type_command 'git -C repo status --short'; git -C repo status --short; finish_terminal; }
ep44_branch_guard() { cd "$TERMINAL_RECORDING_WORKDIR"; begin_terminal; type_command 'git -C repo worktree add ../duplicate main'; if git -C repo worktree add ../duplicate main 2>&1 | sed "s#$TERMINAL_RECORDING_WORKDIR#<lab>#g" | tail -3; then :; else true; fi; type_command 'git -C repo worktree remove ../hotfix'; git -C repo worktree remove ../hotfix; type_command 'git -C repo branch --list'; git -C repo branch --list; finish_terminal; }

ep45_full_bundle() { cd "$TERMINAL_RECORDING_WORKDIR"; begin_terminal; type_command 'git -C source bundle create ../full.bundle --all'; git -C source bundle create ../full.bundle --all >/dev/null 2>&1; type_command 'git -C source bundle verify ../full.bundle'; git -C source bundle verify ../full.bundle 2>&1 | grep -E 'complete history|hash algorithm|okay'; type_command 'git bundle list-heads full.bundle'; git bundle list-heads full.bundle; finish_terminal; }
ep45_clone_bundle() { cd "$TERMINAL_RECORDING_WORKDIR"; begin_terminal; type_command 'git clone full.bundle receiver'; git clone -q full.bundle receiver; type_command 'git -C receiver log --all --graph --oneline --decorate'; git -C receiver log --all --graph --oneline --decorate; type_command 'git -C source rev-parse main'; git -C source rev-parse main; type_command 'git -C receiver rev-parse main'; git -C receiver rev-parse main; finish_terminal; }
ep45_incremental_bundle() { cd "$TERMINAL_RECORDING_WORKDIR"; begin_terminal; type_command 'git -C source bundle create ../update.bundle v1.0..main'; git -C source bundle create ../update.bundle v1.0..main >/dev/null 2>&1; type_command 'git -C receiver bundle verify ../update.bundle'; git -C receiver bundle verify ../update.bundle 2>&1 | grep -E 'prerequisite|hash algorithm|okay'; type_command 'git -C receiver fetch ../update.bundle main'; git -C receiver fetch -q ../update.bundle main; type_command 'git -C receiver merge --ff-only FETCH_HEAD'; git -C receiver merge --ff-only --no-edit FETCH_HEAD | tail -3; finish_terminal; }

ep46_sparse_checkout() { cd "$TERMINAL_RECORDING_WORKDIR/sparse"; begin_terminal; type_command 'git sparse-checkout set app'; git sparse-checkout set app; type_command 'find . -maxdepth 2 -type f | grep -v .git'; find . -maxdepth 2 -type f | grep -v .git; type_command 'git log --oneline -4'; git log --oneline -4; finish_terminal; }
ep46_partial_clone() { cd "$TERMINAL_RECORDING_WORKDIR"; begin_terminal; type_command 'git clone -n --filter=blob:none file://.../remote.git partial'; git clone -q -n --filter=blob:none "file://$PWD/remote.git" partial; type_command 'git -C partial config --get remote.origin.partialclonefilter'; git -C partial config --get remote.origin.partialclonefilter; type_command "git -C partial rev-list --objects --missing=print HEAD | grep -c '^?'"; git -C partial rev-list --objects --missing=print HEAD | grep -c '^?'; type_command 'git -C partial show HEAD:assets/large.bin >/dev/null'; git -C partial show HEAD:assets/large.bin >/dev/null 2>&1; printf 'requested one missing blob on demand\n'; finish_terminal; }
ep46_shallow_clone() { cd "$TERMINAL_RECORDING_WORKDIR"; begin_terminal; type_command 'git clone --depth=2 file://.../remote.git shallow'; git clone -q --depth=2 "file://$PWD/remote.git" shallow; type_command 'git -C shallow rev-parse --is-shallow-repository'; git -C shallow rev-parse --is-shallow-repository; type_command 'git -C shallow log --oneline'; git -C shallow log --oneline; type_command 'git -C shallow fetch --deepen=2'; git -C shallow fetch -q --deepen=2; type_command 'git -C shallow log --oneline'; git -C shallow log --oneline; finish_terminal; }

ep47_classify_files() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; begin_terminal; type_command 'git status --short --ignored'; git status --short --ignored; type_command 'git ls-files'; git ls-files; type_command 'git -C nested rev-parse --is-inside-work-tree'; git -C nested rev-parse --is-inside-work-tree; finish_terminal; }
ep47_dry_runs() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; begin_terminal; type_command 'git clean -nd'; git clean -nd; type_command 'git clean -ndX'; git clean -ndX; type_command 'git clean -ndx'; git clean -ndx; finish_terminal; }
ep47_scoped_clean() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; begin_terminal; type_command 'git clean -ndX -- build/'; git clean -ndX -- build/; type_command 'git clean -fdX -- build/'; git clean -fdX -- build/; type_command 'test -f tracked.txt && test -f notes.txt && echo kept'; test -f tracked.txt && test -f notes.txt && echo kept; type_command 'git -C nested log -1 --oneline'; git -C nested log -1 --oneline; finish_terminal; }

ep48_reflog_protection() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; begin_terminal; type_command 'git reset --hard HEAD^'; git reset --hard HEAD^ | tail -1; type_command 'git reflog -2 --oneline'; git reflog -2 --oneline; type_command 'git fsck --unreachable --no-reflogs'; git fsck --unreachable --no-reflogs 2>/dev/null | head -3; finish_terminal; }
ep48_rescue_commit() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; lost="$(cat ../lost-oid)"; git reset -q --hard HEAD^; git reflog expire --expire=now --all; begin_terminal; type_command 'git fsck --unreachable --no-reflogs'; git fsck --unreachable --no-reflogs 2>/dev/null | head -3; type_command 'git branch rescue <full-object-id>'; git branch rescue "$lost"; type_command 'git log rescue -1 --oneline'; git log rescue -1 --oneline; finish_terminal; }
ep48_prune_object() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; oid="$(cat ../prune-oid)"; git reset -q --hard HEAD^; git reflog expire --expire=now --all; begin_terminal; type_command 'git cat-file -t <full-object-id>'; git cat-file -t "$oid"; type_command 'git gc --prune=now'; git gc --prune=now; type_command 'git cat-file -e <full-object-id> || echo PRUNED'; git cat-file -e "$oid" 2>/dev/null || echo PRUNED; type_command 'git maintenance run --task=commit-graph'; git maintenance run --task=commit-graph; finish_terminal; }

case "${TERMINAL_RECORDING_ID:-}" in
  ep41-add-submodule) ep41_add_submodule;; ep41-gitlink-entry) ep41_gitlink_entry;; ep41-independent-history) ep41_independent_history;;
  ep42-empty-after-clone) ep42_empty_after_clone;; ep42-init-update) ep42_init_update;; ep42-recursive-clone) ep42_recursive_clone;;
  ep43-gitlink-change) ep43_gitlink_change;; ep43-missing-child) ep43_missing_child;; ep43-publish-order) ep43_publish_order;;
  ep44-add-hotfix) ep44_add_hotfix;; ep44-shared-state) ep44_shared_state;; ep44-branch-guard) ep44_branch_guard;;
  ep45-full-bundle) ep45_full_bundle;; ep45-clone-bundle) ep45_clone_bundle;; ep45-incremental-bundle) ep45_incremental_bundle;;
  ep46-sparse-checkout) ep46_sparse_checkout;; ep46-partial-clone) ep46_partial_clone;; ep46-shallow-clone) ep46_shallow_clone;;
  ep47-classify-files) ep47_classify_files;; ep47-dry-runs) ep47_dry_runs;; ep47-scoped-clean) ep47_scoped_clean;;
  ep48-reflog-protection) ep48_reflog_protection;; ep48-rescue-commit) ep48_rescue_commit;; ep48-prune-object) ep48_prune_object;;
  *) printf 'Unknown EP41–48 recording: %s\n' "${TERMINAL_RECORDING_ID:-}" >&2; exit 1;;
esac
