#!/usr/bin/env bash
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_lib.sh"

ep49_porcelain_commit() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; begin_terminal; type_command 'git add app.js'; git add app.js; type_command 'git commit -m "C1 add app"'; GIT_AUTHOR_DATE='2026-06-02T09:00:00+08:00' GIT_COMMITTER_DATE='2026-06-02T09:00:00+08:00' git commit -q -m 'C1 add app'; type_command 'git rev-parse HEAD'; git rev-parse HEAD; finish_terminal; }
ep49_inspect_objects() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; begin_terminal; type_command 'git cat-file -t HEAD && git cat-file -p HEAD'; git cat-file -t HEAD; git cat-file -p HEAD | head -5; type_command 'git ls-tree HEAD'; git ls-tree HEAD; finish_terminal; }
ep49_inspect_state() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; begin_terminal; type_command 'git for-each-ref --format="%(refname) %(objectname)" refs/heads'; git for-each-ref --format='%(refname) %(objectname)' refs/heads; type_command 'git ls-files --stage'; git ls-files --stage; finish_terminal; }

ep50_calculate_oid() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; begin_terminal; type_command 'git rev-parse --show-object-format'; git rev-parse --show-object-format; type_command 'git hash-object app.js'; oid="$(git hash-object app.js)"; printf '%s\n' "$oid"; type_command 'git cat-file -e <oid> || echo NOT_WRITTEN'; git cat-file -e "$oid" 2>/dev/null || echo NOT_WRITTEN; finish_terminal; }
ep50_write_object() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; begin_terminal; type_command 'git hash-object -w app.js'; oid="$(git hash-object -w app.js)"; printf '%s\n' "$oid"; type_command 'git cat-file -t <oid> && git cat-file -s <oid>'; git cat-file -t "$oid"; git cat-file -s "$oid"; type_command 'git cat-file -p <oid>'; git cat-file -p "$oid"; finish_terminal; }
ep50_compare_bytes() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; cp app.js copy.js; printf '\n' >> changed.js; cat app.js >> changed.js; begin_terminal; type_command 'git hash-object app.js copy.js'; git hash-object app.js copy.js; type_command 'git hash-object changed.js'; git hash-object changed.js; type_command 'wc -c app.js changed.js'; wc -c app.js changed.js; finish_terminal; }

ep51_temporary_index() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; blob="$(cat ../blob-oid)"; export GIT_INDEX_FILE="$PWD/.git/lab-index"; begin_terminal; type_command 'GIT_INDEX_FILE=.git/lab-index git read-tree --empty'; git read-tree --empty; type_command 'git update-index --add --cacheinfo 100644,<blob>,app.js'; git update-index --add --cacheinfo "100644,$blob,app.js"; type_command 'git ls-files --stage'; git ls-files --stage; finish_terminal; }
ep51_write_tree() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; blob="$(cat ../blob-oid)"; export GIT_INDEX_FILE="$PWD/.git/lab-index"; git read-tree --empty; git update-index --add --cacheinfo "100644,$blob,app.js"; begin_terminal; type_command 'git write-tree'; tree="$(git write-tree)"; printf '%s\n' "$tree"; type_command 'git cat-file -p <tree>'; git cat-file -p "$tree"; type_command 'git ls-tree -r <tree>'; git ls-tree -r "$tree"; finish_terminal; }
ep51_rename_path() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; blob="$(cat ../blob-oid)"; export GIT_INDEX_FILE="$PWD/.git/lab-index"; git read-tree --empty; git update-index --add --cacheinfo "100644,$blob,app.js"; old="$(git write-tree)"; git update-index --force-remove app.js; git update-index --add --cacheinfo "100644,$blob,src/app.js"; begin_terminal; type_command 'git write-tree'; new="$(git write-tree)"; printf '%s\n' "$new"; type_command 'printf "blob same, tree changed"'; printf 'blob  %s\nold   %s\nnew   %s\n' "$blob" "$old" "$new"; finish_terminal; }

ep52_first_commit() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; tree="$(cat ../tree-oid)"; begin_terminal; type_command 'git commit-tree <tree>'; oid="$(printf 'C1 snapshot\n' | GIT_AUTHOR_DATE='2026-06-03T09:00:00+08:00' GIT_COMMITTER_DATE='2026-06-03T09:00:00+08:00' git commit-tree "$tree")"; printf '%s\n' "$oid"; type_command 'git cat-file -p <commit>'; git cat-file -p "$oid" | head -6; type_command 'git show-ref || echo NO_REFS'; git show-ref || echo NO_REFS; finish_terminal; }
ep52_parent_commit() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; tree="$(cat ../tree-oid)"; first="$(printf 'C1 snapshot\n' | GIT_AUTHOR_DATE='2026-06-03T09:00:00+08:00' GIT_COMMITTER_DATE='2026-06-03T09:00:00+08:00' git commit-tree "$tree")"; begin_terminal; type_command 'git commit-tree <tree> -p <parent>'; second="$(printf 'C2 same tree, new parent\n' | GIT_AUTHOR_DATE='2026-06-04T09:00:00+08:00' GIT_COMMITTER_DATE='2026-06-04T09:00:00+08:00' git commit-tree "$tree" -p "$first")"; printf '%s\n' "$second"; type_command 'git cat-file -p <commit>'; git cat-file -p "$second" | head -7; finish_terminal; }
ep52_annotated_tag() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; second="$(cat ../second-commit)"; begin_terminal; type_command 'git tag -a v-model -m "model snapshot" <commit>'; GIT_COMMITTER_DATE='2026-06-05T09:00:00+08:00' git tag -a v-model -m 'model snapshot' "$second"; type_command 'git rev-parse v-model && git rev-parse v-model^{}'; git rev-parse v-model; git rev-parse 'v-model^{}'; type_command 'git cat-file -p v-model'; git cat-file -p v-model | head -7; finish_terminal; }

ep53_create_branch() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; target="$(cat ../second-commit)"; begin_terminal; type_command 'git show-ref'; git show-ref; type_command 'git update-ref refs/heads/model <oid> ""'; git update-ref refs/heads/model "$target" ''; type_command 'git rev-parse refs/heads/model'; git rev-parse refs/heads/model; finish_terminal; }
ep53_head_guard() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; target="$(cat ../second-commit)"; git update-ref refs/heads/model "$target" ''; begin_terminal; type_command 'git symbolic-ref HEAD refs/heads/model'; git symbolic-ref HEAD refs/heads/model; type_command 'git rev-parse --symbolic-full-name HEAD'; git rev-parse --symbolic-full-name HEAD; type_command 'git update-ref refs/heads/model <oid> <wrong-old>'; git update-ref refs/heads/model "$target" 0000000000000000000000000000000000000000 2>/dev/null || printf 'rejected: ref changed since it was read\n'; finish_terminal; }
ep53_pack_refs() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; target="$(cat ../second-commit)"; git update-ref refs/heads/model "$target" ''; git tag model-lite "$target"; begin_terminal; type_command 'git show-ref --dereference'; git show-ref --dereference; type_command 'git pack-refs --all'; git pack-refs --all; type_command 'git show-ref --dereference'; git show-ref --dereference; printf 'stored in packed-refs; names still resolve\n'; finish_terminal; }

ep54_default_fetch() { cd "$TERMINAL_RECORDING_WORKDIR/local"; begin_terminal; type_command 'git config --get-all remote.origin.fetch'; git config --get-all remote.origin.fetch; type_command 'git for-each-ref --format="%(refname)" refs/remotes'; git for-each-ref --format='%(refname)' refs/remotes; type_command 'git -C ../remote.git for-each-ref --format="%(refname)" refs/heads'; git -C ../remote.git for-each-ref --format='%(refname)' refs/heads; finish_terminal; }
ep54_explicit_fetch() { cd "$TERMINAL_RECORDING_WORKDIR/local"; begin_terminal; type_command 'git fetch origin refs/heads/topic:refs/remotes/origin/topic'; git fetch -q origin refs/heads/topic:refs/remotes/origin/topic; type_command 'git rev-parse origin/topic'; git rev-parse origin/topic; type_command 'git fetch origin refs/heads/topic'; git fetch -q origin refs/heads/topic; git rev-parse FETCH_HEAD; finish_terminal; }
ep54_push_rename() { cd "$TERMINAL_RECORDING_WORKDIR/local"; git fetch -q origin topic; git switch -q -c topic FETCH_HEAD; begin_terminal; type_command 'git push origin refs/heads/topic:refs/heads/review'; git push -q origin refs/heads/topic:refs/heads/review; type_command 'git -C ../remote.git show-ref refs/heads/review'; git -C ../remote.git show-ref refs/heads/review; type_command 'git branch --show-current'; git branch --show-current; finish_terminal; }

ep55_loose_count() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; begin_terminal; type_command 'git count-objects -v'; git count-objects -v | head -5; type_command 'git rev-list --objects --all | tail -3'; git rev-list --objects --all | tail -3; type_command 'git cat-file -s HEAD:data/catalog.txt'; git cat-file -s HEAD:data/catalog.txt; finish_terminal; }
ep55_repack() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; oid="$(git rev-parse HEAD:data/catalog.txt)"; begin_terminal; type_command 'git repack -ad'; git repack -ad; type_command 'git count-objects -v'; git count-objects -v | head -5; type_command 'git cat-file -t <same-oid> && git cat-file -s <same-oid>'; git cat-file -t "$oid"; git cat-file -s "$oid"; finish_terminal; }
ep55_verify_delta() { cd "$TERMINAL_RECORDING_WORKDIR/repo"; git repack -ad; idx="$(find .git/objects/pack -name '*.idx' -print -quit)"; begin_terminal; type_command 'git verify-pack -v .git/objects/pack/*.idx'; git verify-pack -v "$idx" | awk 'NF >= 7 && found < 3 {print; found++}'; type_command 'git verify-pack -v ... | tail -1'; git verify-pack -v "$idx" | tail -1; finish_terminal; }

ep56_fetch_trace() { cd "$TERMINAL_RECORDING_WORKDIR/client"; begin_terminal; type_command 'GIT_TRACE_PACKET=1 git -c protocol.version=2 fetch origin'; GIT_TRACE_PACKET=1 git -c protocol.version=2 fetch origin 2>&1 | sed -E 's/^.*packet: +//' | grep -E 'version 2|command=ls-refs|command=fetch|want |packfile' | head -7; finish_terminal; }
ep56_fetch_result() { cd "$TERMINAL_RECORDING_WORKDIR/client"; remote="$(cat ../remote-tip)"; begin_terminal; type_command 'git cat-file -e <remote-tip> || echo MISSING'; git cat-file -e "$remote" 2>/dev/null || echo MISSING; type_command 'git fetch -q origin'; git fetch -q origin; type_command 'git rev-parse origin/main && git branch --show-current'; git rev-parse origin/main; git branch --show-current; finish_terminal; }
ep56_push_trace() { cd "$TERMINAL_RECORDING_WORKDIR/client"; git fetch -q origin; git reset -q --hard origin/main; printf 'client update\n' >> app.txt; git add app.txt; GIT_AUTHOR_DATE='2026-06-16T09:00:00+08:00' GIT_COMMITTER_DATE='2026-06-16T09:00:00+08:00' git commit -q -m 'C3 client update'; begin_terminal; type_command 'GIT_TRACE_PACKET=1 git push origin main'; GIT_TRACE_PACKET=1 git push origin main 2>&1 | sed -E 's/^.*packet: +//' | awk '/receive-pack>.*refs\/heads\/main/ && !advertised {print "receive-pack> advertise refs/heads/main"; advertised=1} /push>.*refs\/heads\/main/ {print "push> update refs/heads/main"} /receive-pack> unpack ok/ {print} /receive-pack> ok refs\/heads\/main/ {print}'; type_command 'git -C ../remote.git rev-parse main'; git -C ../remote.git rev-parse main; finish_terminal; }

case "${TERMINAL_RECORDING_ID:-}" in
  ep49-porcelain-commit) ep49_porcelain_commit;; ep49-inspect-objects) ep49_inspect_objects;; ep49-inspect-state) ep49_inspect_state;;
  ep50-calculate-oid) ep50_calculate_oid;; ep50-write-object) ep50_write_object;; ep50-compare-bytes) ep50_compare_bytes;;
  ep51-temporary-index) ep51_temporary_index;; ep51-write-tree) ep51_write_tree;; ep51-rename-path) ep51_rename_path;;
  ep52-first-commit) ep52_first_commit;; ep52-parent-commit) ep52_parent_commit;; ep52-annotated-tag) ep52_annotated_tag;;
  ep53-create-branch) ep53_create_branch;; ep53-head-guard) ep53_head_guard;; ep53-pack-refs) ep53_pack_refs;;
  ep54-default-fetch) ep54_default_fetch;; ep54-explicit-fetch) ep54_explicit_fetch;; ep54-push-rename) ep54_push_rename;;
  ep55-loose-count) ep55_loose_count;; ep55-repack) ep55_repack;; ep55-verify-delta) ep55_verify_delta;;
  ep56-fetch-trace) ep56_fetch_trace;; ep56-fetch-result) ep56_fetch_result;; ep56-push-trace) ep56_push_trace;;
  *) printf 'Unknown EP49–56 recording: %s\n' "${TERMINAL_RECORDING_ID:-}" >&2; exit 1;;
esac
