export {BrowserEvidenceScene} from './browser/BrowserEvidenceScene';
export {BrowserFocusScene} from './browser/BrowserFocusScene';
export {BrowserPanel} from './browser/BrowserPanel';
export type {BrowserFocusRegion, BrowserRecordingMetadata, BrowserRecordingSource} from './browser/types';
export {GITHUB_COURSE_INTRO_DURATION, GitHubCourseIntro} from './brand/GitHubCourseIntro';
export {GITHUB_COURSE_OUTRO_DURATION, GitHubCourseOutro} from './brand/GitHubCourseOutro';
export {GitHubMark, GitHubPlatformGlyph, GitMark} from './brand/BrandPrimitives';
export {GitHubStateBridge} from './bridge/GitHubStateBridge';
export {GitHubNarrationSubtitle} from './caption/GitHubNarrationSubtitle';
export type {GitHubNarrationCue} from './caption/GitHubNarrationSubtitle';
export {GitHubCourseLayout} from './layout/GitHubCourseLayout';
export {PlatformStateLegend} from './platform/PlatformStateLegend';
