// Generated by scripts/git-course.mjs from git-course/episodes/*.json.
// Do not edit by hand.
import {seconds} from '../timeline';

export const EP01_SCENES = [
  {id: "hook", title: "问题", duration: seconds(12)},
  {id: "bad-model", title: "错误模型", duration: seconds(22)},
  {id: "version-control", title: "版本控制", duration: seconds(30)},
  {id: "snapshot-model", title: "快照流", duration: seconds(32)},
  {id: "practice-check", title: "实践验证", duration: seconds(30)},
  {id: "local-history", title: "本地历史", duration: seconds(30)},
  {id: "integrity", title: "完整性", duration: seconds(30)},
  {id: "takeaway", title: "结论", duration: seconds(24)},
] as const;
export const EP01_DURATION_IN_FRAMES = EP01_SCENES.reduce((sum, scene) => sum + scene.duration, 0);

export const EP02_SCENES = [
  {id: "hook", title: "问题", duration: seconds(12)},
  {id: "three-areas", title: "三层结构", duration: seconds(26)},
  {id: "modify", title: "修改", duration: seconds(30)},
  {id: "add", title: "暂存", duration: seconds(36)},
  {id: "edit-after-add", title: "再次修改", duration: seconds(30)},
  {id: "commit", title: "提交", duration: seconds(30)},
  {id: "takeaway", title: "结论", duration: seconds(16)},
] as const;
export const EP02_DURATION_IN_FRAMES = EP02_SCENES.reduce((sum, scene) => sum + scene.duration, 0);

export const EP03_SCENES = [
  {id: "hook", title: "问题", duration: seconds(10)},
  {id: "from-index", title: "读取 Index", duration: seconds(24)},
  {id: "object-model", title: "对象模型", duration: seconds(30)},
  {id: "commit-fields", title: "commit 字段", duration: seconds(24)},
  {id: "parent-chain", title: "parent", duration: seconds(22)},
  {id: "hash-identity", title: "hash", duration: seconds(22)},
  {id: "takeaway", title: "结论", duration: seconds(18)},
] as const;
export const EP03_DURATION_IN_FRAMES = EP03_SCENES.reduce((sum, scene) => sum + scene.duration, 0);

export const EP04_SCENES = [
  {id: "hook", title: "问题", duration: seconds(12)},
  {id: "mental-model", title: "模型", duration: seconds(18)},
  {id: "terminal", title: "命令", duration: seconds(18)},
  {id: "branch-write", title: "写入 ref", duration: seconds(22)},
  {id: "branch-result", title: "分支出现", duration: seconds(28)},
  {id: "switch", title: "HEAD 切换", duration: seconds(24)},
  {id: "commit", title: "feature 前进", duration: seconds(32)},
  {id: "compare", title: "对比", duration: seconds(14)},
  {id: "takeaway", title: "结论", duration: seconds(12)},
] as const;
export const EP04_DURATION_IN_FRAMES = EP04_SCENES.reduce((sum, scene) => sum + scene.duration, 0);

export const EP05_SCENES = [
  {id: "hook", title: "问题", duration: seconds(12)},
  {id: "symbolic-ref", title: "符号引用", duration: seconds(22)},
  {id: "terminal", title: "命令", duration: seconds(22)},
  {id: "switch", title: "HEAD 切换", duration: seconds(32)},
  {id: "commit-current", title: "当前分支前进", duration: seconds(32)},
  {id: "detached", title: "分离 HEAD", duration: seconds(36)},
  {id: "takeaway", title: "总结", duration: seconds(24)},
] as const;
export const EP05_DURATION_IN_FRAMES = EP05_SCENES.reduce((sum, scene) => sum + scene.duration, 0);

export const EP06_SCENES = [
  {id: "hook", title: "问题", duration: seconds(12)},
  {id: "fast-forward", title: "快进", duration: seconds(30)},
  {id: "diverged", title: "分叉", duration: seconds(26)},
  {id: "three-way", title: "三方合并", duration: seconds(40)},
  {id: "merge-commit", title: "合并提交", duration: seconds(30)},
  {id: "conflict", title: "冲突", duration: seconds(28)},
  {id: "takeaway", title: "结论", duration: seconds(14)},
] as const;
export const EP06_DURATION_IN_FRAMES = EP06_SCENES.reduce((sum, scene) => sum + scene.duration, 0);

export const EP07_SCENES = [
  {id: "hook", title: "问题", duration: seconds(12)},
  {id: "compare-merge", title: "对比 merge", duration: seconds(26)},
  {id: "replay-model", title: "重放模型", duration: seconds(44)},
  {id: "new-identity", title: "新身份", duration: seconds(30)},
  {id: "fast-forward-after", title: "快进", duration: seconds(26)},
  {id: "public-risk", title: "公开历史", duration: seconds(28)},
  {id: "takeaway", title: "结论", duration: seconds(14)},
] as const;
export const EP07_DURATION_IN_FRAMES = EP07_SCENES.reduce((sum, scene) => sum + scene.duration, 0);

export const EP08_SCENES = [
  {id: "hook", title: "问题", duration: seconds(12)},
  {id: "three-trees", title: "三棵树", duration: seconds(28)},
  {id: "reset-modes", title: "reset", duration: seconds(46)},
  {id: "revert", title: "revert", duration: seconds(30)},
  {id: "restore", title: "restore", duration: seconds(30)},
  {id: "choose", title: "选择", duration: seconds(22)},
  {id: "takeaway", title: "总结", duration: seconds(12)},
] as const;
export const EP08_DURATION_IN_FRAMES = EP08_SCENES.reduce((sum, scene) => sum + scene.duration, 0);
