// Generated by scripts/git-course.mjs from git-course/episodes/*.json.
// Do not edit by hand.
import {seconds} from '../timeline';

export const EP01_SCENES = [
  {id: "hook", title: "问题", duration: seconds(12)},
  {id: "bad-model", title: "错误模型", duration: seconds(22)},
  {id: "version-control", title: "版本控制", duration: seconds(31)},
  {id: "snapshot-model", title: "快照流", duration: seconds(31)},
  {id: "practice-check", title: "实践验证", duration: seconds(30)},
  {id: "local-history", title: "本地历史", duration: seconds(30)},
  {id: "integrity", title: "完整性", duration: seconds(30)},
  {id: "takeaway", title: "结论", duration: seconds(24)},
] as const;
export const EP01_DURATION_IN_FRAMES = EP01_SCENES.reduce((sum, scene) => sum + scene.duration, 0);

export const EP02_SCENES = [
  {id: "hook", title: "问题", duration: seconds(12)},
  {id: "three-areas", title: "三层结构", duration: seconds(26)},
  {id: "modify", title: "修改", duration: seconds(30)},
  {id: "add", title: "暂存", duration: seconds(36)},
  {id: "edit-after-add", title: "再次修改", duration: seconds(30)},
  {id: "commit", title: "提交", duration: seconds(30)},
  {id: "takeaway", title: "结论", duration: seconds(16)},
] as const;
export const EP02_DURATION_IN_FRAMES = EP02_SCENES.reduce((sum, scene) => sum + scene.duration, 0);

export const EP03_SCENES = [
  {id: "hook", title: "问题", duration: seconds(10)},
  {id: "from-index", title: "读取 Index", duration: seconds(24)},
  {id: "object-model", title: "对象模型", duration: seconds(30)},
  {id: "commit-fields", title: "commit 字段", duration: seconds(24)},
  {id: "parent-chain", title: "parent", duration: seconds(22)},
  {id: "hash-identity", title: "hash", duration: seconds(22)},
  {id: "takeaway", title: "结论", duration: seconds(18)},
] as const;
export const EP03_DURATION_IN_FRAMES = EP03_SCENES.reduce((sum, scene) => sum + scene.duration, 0);

export const EP04_SCENES = [
  {id: "hook", title: "问题", duration: seconds(12)},
  {id: "mental-model", title: "模型", duration: seconds(18)},
  {id: "terminal", title: "命令", duration: seconds(18)},
  {id: "branch-write", title: "写入 ref", duration: seconds(22)},
  {id: "ref-storage", title: "ref 存在哪里", duration: seconds(28)},
  {id: "branch-result", title: "分支出现", duration: seconds(24)},
  {id: "start-point", title: "指针可以从哪里开始", duration: seconds(24)},
  {id: "switch", title: "HEAD 切换", duration: seconds(24)},
  {id: "commit", title: "feature 前进", duration: seconds(32)},
  {id: "compare", title: "对比", duration: seconds(18)},
  {id: "takeaway", title: "结论", duration: seconds(20)},
] as const;
export const EP04_DURATION_IN_FRAMES = EP04_SCENES.reduce((sum, scene) => sum + scene.duration, 0);

export const EP05_SCENES = [
  {id: "hook", title: "问题", duration: seconds(16), captions: [{"from":4.9,"to":7.7,"text":"它不是最新提交，也不是隐藏分支"},{"from":8.1,"to":11.2,"text":"HEAD 是 Git 当前操作的入口"},{"from":11.6,"to":15.6,"text":"它决定下一次提交接到哪条历史后面"}]},
  {id: "symbolic-ref", title: "符号引用", duration: seconds(40), captions: [{"from":0.8,"to":5,"text":"先分清：文件保存内容和最终解析结果"},{"from":5.4,"to":12.8,"text":".git/HEAD 保存的是 branch ref"},{"from":15.4,"to":18.2,"text":"这段内容叫 symbolic ref"},{"from":19.8,"to":24.4,"text":"branch ref 保存末端 commit ID"},{"from":24.8,"to":29,"text":"文件保存的内容，不等于最终解析结果"},{"from":29.3,"to":33,"text":"HEAD → main → C2"},{"from":33.3,"to":39.6,"text":"历史再沿 commit 的 parent 展开"}]},
  {id: "terminal", title: "命令", duration: seconds(30), captions: [{"from":1,"to":6,"text":"symbolic-ref：查看当前 branch"},{"from":6.4,"to":12,"text":"cat .git/HEAD：查看保存的 ref"},{"from":12.4,"to":18.4,"text":"rev-parse HEAD：得到最终 commit"},{"from":18.8,"to":25.6,"text":"三条命令，停在引用链的不同层级"}]},
  {id: "switch", title: "HEAD 切换", duration: seconds(26), captions: [{"from":0.8,"to":4.2,"text":"这里只核对 HEAD 文件的变化"},{"from":4.6,"to":10.2,"text":"切换前：HEAD → main"},{"from":13.3,"to":17.1,"text":"切换后：HEAD → feature"},{"from":17.4,"to":20.5,"text":"两个 branch 都在 C2，commit 图不变"},{"from":20.8,"to":21.7,"text":"改变的是当前入口"},{"from":22,"to":25.6,"text":"Index 与 Working Tree 对齐 feature"}]},
  {id: "commit-current", title: "当前分支前进", duration: seconds(34), captions: [{"from":0.8,"to":7.2,"text":"提交前：HEAD → feature → C2"},{"from":7.5,"to":12.2,"text":"先创建以 C2 为 parent 的 C3"},{"from":12.6,"to":19.4,"text":"feature ref：C2 → C3"},{"from":19.8,"to":25,"text":"HEAD 文件不变，仍然指向 feature"},{"from":25.4,"to":32.2,"text":"因此解析后的 HEAD 也变成 C3"}]},
  {id: "detached", title: "分离 HEAD", duration: seconds(32), captions: [{"from":0.5,"to":1.9,"text":"detached HEAD 有什么用？"},{"from":2.2,"to":6.8,"text":"查看 C1，但不移动 main 或 feature"},{"from":7.1,"to":13.8,"text":"HEAD 直接保存 C1 的 commit ID"},{"from":14.6,"to":17,"text":"现有 branch 保持不动"},{"from":20.3,"to":22.3,"text":"只查看，完成后切回原 branch"},{"from":22.6,"to":29.8,"text":"继续修改，先创建一个新 branch"}]},
  {id: "takeaway", title: "总结", duration: seconds(20), captions: [{"from":4,"to":7.7,"text":"正常：HEAD → branch → commit"},{"from":8.4,"to":11.8,"text":"detached：HEAD 直接保存 commit ID"},{"from":12.7,"to":17,"text":"判断当前位置，先问 HEAD 跟着谁"}]},
] as const;
export const EP05_DURATION_IN_FRAMES = EP05_SCENES.reduce((sum, scene) => sum + scene.duration, 0);

export const EP06_SCENES = [
  {id: "hook", title: "问题", duration: seconds(11), captions: [{"from":0.35,"to":3.26,"text":"merge 把另一分支的工作接入当前分支"},{"from":3.887,"to":5.953,"text":"Git 不揉文件夹，而是先看提交图"},{"from":6.467,"to":9.944,"text":"能沿历史追上目标就快进；已经分叉，才合成新快照"}]},
  {id: "fast-forward", title: "快进", duration: seconds(32), captions: [{"from":0.35,"to":1.655,"text":"先看没有分叉的情况"},{"from":2.071,"to":7.711,"text":"main 停在 C2，hotfix 从 C2 继续提交到了 C3，因此 C2 是 C3 的祖先"},{"from":8.218,"to":13.998,"text":"在 main 上执行 git merge hotfix，默认不用计算新快照，也不用创建 merge commit"},{"from":14.556,"to":19.962,"text":"Git 只把 main 从 C2 移到 C3；hotfix 不变，HEAD 仍跟着 main"},{"from":20.63,"to":24.468,"text":"这叫 fast-forward：当前分支沿已有的 parent 链追上目标"},{"from":25.001,"to":31.142,"text":"它接入了 hotfix 的工作，却不额外制造汇合节点；所以没有新 commit 也是正常结果"}]},
  {id: "diverged", title: "分叉", duration: seconds(25), captions: [{"from":0.35,"to":4.226,"text":"一旦 main 和 feature 都从 C2 继续提交，历史就分叉了"},{"from":4.808,"to":9.353,"text":"main 到了 C3，feature 到了 C4，任何一边都不是另一边的祖先"},{"from":9.898,"to":14.813,"text":"如果直接把 main 移到 C4，main 上的 C3 就会被绕开，所以 fast-forward 不成立"},{"from":15.458,"to":19.102,"text":"Git 必须先找到双方的 merge base，也就是共同祖先 C2"},{"from":19.737,"to":23.91,"text":"它的作用，是把双方原本共有的内容与后来各自引入的修改分开"}]},
  {id: "three-way", title: "三方合并", duration: seconds(45), captions: [{"from":0.35,"to":3.026,"text":"找到 merge base 后，Git 才开始三方合并"},{"from":3.586,"to":5.996,"text":"它比较的不是两个目录，而是三个快照"},{"from":6.743,"to":15.487,"text":"base 是共同祖先 C2，ours 是 HEAD 当前所在的 main，也就是 C3，theirs 是要合进来的 feature，也就是 C4"},{"from":16.079,"to":19.641,"text":"Git 先计算 base 到 ours 的变化，再计算 base 到 theirs 的变化"},{"from":20.297,"to":26.505,"text":"如果两边修改了不同文件，或者同一文件中能够独立合并的区域，Git 可以把这些变化组合成一个结果快照"},{"from":27.084,"to":33.067,"text":"注意 ours 和 theirs 取决于你站在哪条分支上执行 merge，并不是永远等于 main 和 feature"},{"from":33.748,"to":37.303,"text":"三方比较让 Git 区分原有内容和双方后来引入的修改"},{"from":37.868,"to":43.251,"text":"能自动组合的变化先形成 result；接下来，Git 还要把它写进历史"}]},
  {id: "merge-commit", title: "合并提交", duration: seconds(34), captions: [{"from":0.35,"to":4.979,"text":"有了 result，Git 先把它写成新的 tree，再创建 merge commit M1"},{"from":5.605,"to":9.467,"text":"前面讲过，普通提交通常记录一个 parent；M1 则同时记录两个"},{"from":10.001,"to":18.125,"text":"第一个 parent 是执行 merge 前 HEAD 所在的 main，也就是 C3；另一个是合入的 feature，也就是 C4"},{"from":18.663,"to":22.89,"text":"随后 main 移动到 M1，feature 仍然停在 C4，HEAD 继续跟着 main"},{"from":23.45,"to":28.171,"text":"C3 和 C4 都没有被改写，两个 parent 明确保留了它们的来源和汇合位置"},{"from":28.789,"to":32.192,"text":"以后沿任意一条 parent 边向后遍历，都能回到各自的开发线"}]},
  {id: "conflict", title: "冲突", duration: seconds(34), captions: [{"from":0.35,"to":4.777,"text":"如果内容或路径变化无法自动组合，merge 会暂停，不会替你选边"},{"from":5.449,"to":10.682,"text":"冲突文件会出现标记，Index 保存未合并状态；merge commit 此时还不存在"},{"from":11.228,"to":16.559,"text":"读完 ours 和 theirs 后，编辑出正确内容，再用 git add 把解决结果写入 Index"},{"from":17.072,"to":20.535,"text":"没有未合并路径后，执行 git commit 完成 merge"},{"from":21.089,"to":24.025,"text":"所以冲突不是 Git 损坏，而是它无法推断业务意图"},{"from":24.676,"to":29.19,"text":"如果方向不对，可以在完成前运行 git merge --abort，尝试回到开始前"},{"from":29.806,"to":32.619,"text":"为了让恢复可靠，合并前应先保持工作区干净"}]},
  {id: "takeaway", title: "结论", duration: seconds(27), captions: [{"from":0.25,"to":3.143,"text":"现在把成功合并和冲突暂停两条路径收在一起"},{"from":3.631,"to":9.157,"text":"当前分支是目标分支的祖先时，默认 fast-forward：接入工作，只移动 branch"},{"from":9.71,"to":13.959,"text":"历史分叉，就找 merge base，比较 base、ours 和 theirs"},{"from":14.563,"to":20.769,"text":"能组合便创建保留两条来源的 merge commit；不能判断就暂停处理冲突"},{"from":21.458,"to":24.995,"text":"merge 的价值，是整合另一条历史，又不改写已有提交"}]},
] as const;
export const EP06_DURATION_IN_FRAMES = EP06_SCENES.reduce((sum, scene) => sum + scene.duration, 0);

export const EP07_SCENES = [
  {id: "hook", title: "问题", duration: seconds(14)},
  {id: "compare-merge", title: "对比 merge", duration: seconds(32)},
  {id: "replay-model", title: "重放模型", duration: seconds(58)},
  {id: "new-identity", title: "新身份", duration: seconds(40)},
  {id: "fast-forward-after", title: "快进", duration: seconds(34)},
  {id: "public-risk", title: "公开历史", duration: seconds(38)},
  {id: "takeaway", title: "结论", duration: seconds(24)},
] as const;
export const EP07_DURATION_IN_FRAMES = EP07_SCENES.reduce((sum, scene) => sum + scene.duration, 0);

export const EP08_SCENES = [
  {id: "hook", title: "问题", duration: seconds(14)},
  {id: "three-trees", title: "三棵树", duration: seconds(34)},
  {id: "reset-modes", title: "reset", duration: seconds(58)},
  {id: "revert", title: "revert", duration: seconds(38)},
  {id: "restore", title: "restore", duration: seconds(42)},
  {id: "choose", title: "选择", duration: seconds(30)},
  {id: "takeaway", title: "总结", duration: seconds(24)},
] as const;
export const EP08_DURATION_IN_FRAMES = EP08_SCENES.reduce((sum, scene) => sum + scene.duration, 0);
