// Generated by scripts/terminal-recordings/build-metadata.mjs.
// Re-run record-asciinema.sh instead of editing this file.
export const TERMINAL_RECORDINGS = {
  "ep01-log": {"id":"ep01-log","durationInFrames":95,"holdFromFrame":34,"width":1420,"height":768,"fps":30,"font":"Source Code Pro Medium","fontSize":32,"lineHeight":1.6,"theme":"git-course-termius-dark"},
  "ep01-show-name-only": {"id":"ep01-show-name-only","durationInFrames":104,"holdFromFrame":43,"width":1420,"height":768,"fps":30,"font":"Source Code Pro Medium","fontSize":32,"lineHeight":1.6,"theme":"git-course-termius-dark"},
  "ep01-show-stat": {"id":"ep01-show-stat","durationInFrames":98,"holdFromFrame":37,"width":1420,"height":768,"fps":30,"font":"Source Code Pro Medium","fontSize":32,"lineHeight":1.6,"theme":"git-course-termius-dark"},
  "ep02-add": {"id":"ep02-add","durationInFrames":168,"holdFromFrame":107,"width":1420,"height":768,"fps":30,"font":"Source Code Pro Medium","fontSize":32,"lineHeight":1.6,"theme":"git-course-termius-dark"},
  "ep02-commit": {"id":"ep02-commit","durationInFrames":197,"holdFromFrame":136,"width":1420,"height":768,"fps":30,"font":"Source Code Pro Medium","fontSize":32,"lineHeight":1.6,"theme":"git-course-termius-dark"},
  "ep02-status-mm": {"id":"ep02-status-mm","durationInFrames":96,"holdFromFrame":35,"width":1420,"height":768,"fps":30,"font":"Source Code Pro Medium","fontSize":32,"lineHeight":1.6,"theme":"git-course-termius-dark"},
  "ep03-commit": {"id":"ep03-commit","durationInFrames":208,"holdFromFrame":147,"width":1420,"height":768,"fps":30,"font":"Source Code Pro Medium","fontSize":32,"lineHeight":1.6,"theme":"git-course-termius-dark"},
  "ep04-branch-flow": {"id":"ep04-branch-flow","durationInFrames":310,"holdFromFrame":249,"width":1420,"height":768,"fps":30,"font":"Source Code Pro Medium","fontSize":32,"lineHeight":1.6,"theme":"git-course-termius-dark"},
  "ep05-head-flow": {"id":"ep05-head-flow","durationInFrames":363,"holdFromFrame":302,"width":1420,"height":768,"fps":30,"font":"Source Code Pro Medium","fontSize":32,"lineHeight":1.6,"theme":"git-course-termius-dark"},
  "ep06-merge-conflict": {"id":"ep06-merge-conflict","durationInFrames":210,"holdFromFrame":149,"width":1420,"height":768,"fps":30,"font":"Source Code Pro Medium","fontSize":32,"lineHeight":1.6,"theme":"git-course-termius-dark"},
  "ep07-rebase-flow": {"id":"ep07-rebase-flow","durationInFrames":510,"holdFromFrame":449,"width":1420,"height":768,"fps":30,"font":"Source Code Pro Medium","fontSize":32,"lineHeight":1.6,"theme":"git-course-termius-dark"},
  "ep08-reset-hard": {"id":"ep08-reset-hard","durationInFrames":198,"holdFromFrame":137,"width":1420,"height":768,"fps":30,"font":"Source Code Pro Medium","fontSize":32,"lineHeight":1.6,"theme":"git-course-termius-dark"},
  "ep08-reset-mixed": {"id":"ep08-reset-mixed","durationInFrames":157,"holdFromFrame":96,"width":1420,"height":768,"fps":30,"font":"Source Code Pro Medium","fontSize":32,"lineHeight":1.6,"theme":"git-course-termius-dark"},
  "ep08-reset-soft": {"id":"ep08-reset-soft","durationInFrames":137,"holdFromFrame":76,"width":1420,"height":768,"fps":30,"font":"Source Code Pro Medium","fontSize":32,"lineHeight":1.6,"theme":"git-course-termius-dark"},
  "ep08-restore-flow": {"id":"ep08-restore-flow","durationInFrames":500,"holdFromFrame":439,"width":1420,"height":768,"fps":30,"font":"Source Code Pro Medium","fontSize":32,"lineHeight":1.6,"theme":"git-course-termius-dark"},
  "ep08-revert": {"id":"ep08-revert","durationInFrames":278,"holdFromFrame":217,"width":1420,"height":768,"fps":30,"font":"Source Code Pro Medium","fontSize":32,"lineHeight":1.6,"theme":"git-course-termius-dark"},
} as const;
