import {AbsoluteFill,interpolate,useCurrentFrame} from 'remotion'; import {EP19} from '../data/episodes'; import {EP19_DURATION_IN_FRAMES,EP19_SCENES} from '../data/episodeTimelines.generated'; import {TERMINAL_RECORDINGS} from '../data/terminalRecordings.generated';
import {CourseCommitNode,CourseGraphEdge,CourseLayout,EpisodeTitleCard,EpisodeTimeline,NarrationSubtitle,RecordedTerminalCueSequence,SceneTitle,createEpisodeRuntime,courseCommitAnchor} from '../kit'; import {COLOR,WEIGHT} from '../palette'; import {seconds} from '../timeline'; import {TYPE} from '../typography';
export {EP19_DURATION_IN_FRAMES,EP19_SCENES}; const R=createEpisodeRuntime(EP19_SCENES); const ap=(f:number,a:number)=>interpolate(f,[seconds(a),seconds(a+.7)],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}); const cue=(id:keyof typeof TERMINAL_RECORDINGS,d:number)=>({id,from:0,durationInFrames:seconds(d+.7),src:`git-course-lab/terminal/${id}.mp4`,holdFrameSrc:`git-course-lab/terminal/${id}-hold.png`,holdFromFrame:TERMINAL_RECORDINGS[id].holdFromFrame});
const Graph=({picked=false}:{picked?:boolean})=>{const nodes=[[360,520,'C0'],[690,350,'F1'],[990,350,'F2'],[1290,350,'F3'],[690,690,'M1']];return <svg width="1500" height="760" viewBox="0 0 1500 760" style={{margin:'170px auto 0'}}><g><CourseGraphEdge from={courseCommitAnchor(690,350,{size:'hero'})} to={courseCommitAnchor(360,520,{size:'hero'})} size="hero"/><CourseGraphEdge from={courseCommitAnchor(990,350,{size:'hero'})} to={courseCommitAnchor(690,350,{size:'hero'})} size="hero"/><CourseGraphEdge from={courseCommitAnchor(1290,350,{size:'hero'})} to={courseCommitAnchor(990,350,{size:'hero'})} size="hero"/><CourseGraphEdge from={courseCommitAnchor(690,690,{size:'hero'})} to={courseCommitAnchor(360,520,{size:'hero'})} size="hero"/>{picked?<CourseGraphEdge from={courseCommitAnchor(1050,690,{size:'hero'})} to={courseCommitAnchor(690,690,{size:'hero'})} size="hero"/>:null}</g><g>{nodes.map((n,i)=><CourseCommitNode key={n[2]} x={n[0] as number} y={n[1] as number} id={n[2] as string} size="hero" tone={i===2?'feature':'default'}/>) }{picked?<CourseCommitNode x={1050} y={690} id="P2" size="hero" tone="main"/>:null}</g></svg>};
const Term:React.FC<{scene:string;id:keyof typeof TERMINAL_RECORDINGS;d:number;model?:React.ReactNode}>=({scene,id,d,model})=>{const f=useCurrentFrame();return <AbsoluteFill><RecordedTerminalCueSequence cues={[cue(id,d)]} rect={{x:250,y:132,width:1420,height:720}} auditIdPrefix={`ep19-${scene}-terminal`}/>{model?<AbsoluteFill style={{background:COLOR.canvas.base,opacity:ap(f,d)}}>{model}</AbsoluteFill>:null}<NarrationSubtitle frame={f} cues={R.captions(scene as never)} width={1320} bottom={64}/></AbsoluteFill>};
// @git-course-scene hook:start
const Hook=()=>{const f=useCurrentFrame();return <AbsoluteFill><EpisodeTitleCard index="19." keyword="只要 F2" suffix="怎么拿？" opacity={1} underlineScale={ap(f,.4)} auditId="ep19-hook"/><NarrationSubtitle frame={f} cues={R.captions('hook')} width={1320} bottom={64}/></AbsoluteFill>};
// @git-course-scene hook:end
// @git-course-scene source-history:start
const SourceHistory=()=>{const f=useCurrentFrame();return <AbsoluteFill><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>Source 与 Target 拥有不同 Parent</SceneTitle><Graph/><NarrationSubtitle frame={f} cues={R.captions('source-history')} width={1320} bottom={64}/></AbsoluteFill>};
// @git-course-scene source-history:end
// @git-course-scene inspect-patch:start
const InspectPatch=()=> <Term scene="inspect-patch" id="ep19-show" d={10} model={<><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>先验证 Source Patch</SceneTitle><Graph/></>}/>;
// @git-course-scene inspect-patch:end
// @git-course-scene pick-change:start
const PickChange=()=> <Term scene="pick-change" id="ep19-pick" d={10} model={<><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>复制变化，在 M1 后创建 P2</SceneTitle><Graph picked/></>}/>;
// @git-course-scene pick-change:end
// @git-course-scene compare-identity:start
const CompareIdentity=()=> <Term scene="compare-identity" id="ep19-compare" d={9} model={<div style={{padding:'130px 230px'}}><SceneTitle>Patch 可以相同，Commit 身份仍不同</SceneTitle><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:46,marginTop:100}}>{[['F2','parent: F1'],['P2','parent: M1']].map((x,i)=><div key={x[0]} style={{padding:44,borderRadius:26,background:COLOR.canvas.raised,border:`3px solid ${i?COLOR.git.main:COLOR.git.feature}`}}><div style={{...TYPE.hero,fontWeight:WEIGHT.bold}}>{x[0]}</div><div style={{...TYPE.title,marginTop:28}}>{x[1]}</div><div style={{...TYPE.body,marginTop:20,color:COLOR.text.secondary}}>OID differs · patch matches</div></div>)}</div></div>}/>;
// @git-course-scene compare-identity:end
// @git-course-scene conflict-boundary:start
const ConflictBoundary=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{padding:'130px 230px'}}><SceneTitle>冲突时，仍回到 Index 状态</SceneTitle><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:34,marginTop:110}}>{['unmerged','resolve + add','continue / abort'].map((x,i)=><div key={x} style={{padding:38,borderRadius:24,background:COLOR.canvas.raised,textAlign:'center',opacity:ap(f,2+i*3),...TYPE.title,fontWeight:WEIGHT.bold}}>{x}</div>)}</div><NarrationSubtitle frame={f} cues={R.captions('conflict-boundary')} width={1320} bottom={64}/></AbsoluteFill>};
// @git-course-scene conflict-boundary:end
// @git-course-scene takeaway:start
const Takeaway=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{padding:'130px 220px'}}><SceneTitle>选择变化，不是移动 Commit</SceneTitle><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:26,marginTop:110}}>{['locate','show','cherry-pick','compare'].map((x,i)=><div key={x} style={{padding:34,borderRadius:22,background:COLOR.canvas.raised,textAlign:'center',opacity:ap(f,2+i*2.4),...TYPE.title,fontWeight:WEIGHT.bold}}>{x}</div>)}</div><NarrationSubtitle frame={f} cues={R.captions('takeaway')} width={1320} bottom={64}/></AbsoluteFill>};
// @git-course-scene takeaway:end
const C={hook:Hook,'source-history':SourceHistory,'inspect-patch':InspectPatch,'pick-change':PickChange,'compare-identity':CompareIdentity,'conflict-boundary':ConflictBoundary,takeaway:Takeaway}; export const Ep19CherryPick=()=>{const f=useCurrentFrame();return <CourseLayout seriesTitle={EP19.seriesTitle} episodeTitle={EP19.title} scenes={EP19_SCENES} currentFrame={f} showHeader={x=>x>=R.start('source-history')} showEpisodeTitle={x=>x>=R.start('source-history')}><EpisodeTimeline runtime={R} components={C}/></CourseLayout>};
