import {AbsoluteFill,interpolate,useCurrentFrame} from 'remotion'; import {EP20} from '../data/episodes'; import {EP20_DURATION_IN_FRAMES,EP20_SCENES} from '../data/episodeTimelines.generated'; import {TERMINAL_RECORDINGS} from '../data/terminalRecordings.generated'; import {CourseLayout,EpisodeTitleCard,EpisodeTimeline,NarrationSubtitle,RecordedTerminalCueSequence,SceneTitle,createEpisodeRuntime} from '../kit'; import {COLOR,FONT,WEIGHT} from '../palette'; import {seconds} from '../timeline'; import {TYPE} from '../typography';
export {EP20_DURATION_IN_FRAMES,EP20_SCENES}; const R=createEpisodeRuntime(EP20_SCENES); const ap=(f:number,a:number)=>interpolate(f,[seconds(a),seconds(a+.7)],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}); const cue=(id:keyof typeof TERMINAL_RECORDINGS,d:number)=>({id,from:0,durationInFrames:seconds(d+.7),src:`git-course-lab/terminal/${id}.mp4`,holdFrameSrc:`git-course-lab/terminal/${id}-hold.png`,holdFromFrame:TERMINAL_RECORDINGS[id].holdFromFrame});
const Term:React.FC<{scene:string;id:keyof typeof TERMINAL_RECORDINGS;d:number;model?:React.ReactNode}>=({scene,id,d,model})=>{const f=useCurrentFrame();return <AbsoluteFill><RecordedTerminalCueSequence cues={[cue(id,d)]} rect={{x:250,y:132,width:1420,height:720}} auditIdPrefix={`ep20-${scene}-terminal`}/>{model?<AbsoluteFill style={{background:COLOR.canvas.base,opacity:ap(f,d)}}>{model}</AbsoluteFill>:null}<NarrationSubtitle frame={f} cues={R.captions(scene as never)} width={1320} bottom={64}/></AbsoluteFill>};
const ObjectFields=()=> <div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:24,width:1420,margin:'300px auto 0'}}>{['tree','parent','author','committer','message'].map((x,i)=><div key={x} style={{padding:'38px 22px',borderRadius:22,background:COLOR.canvas.raised,textAlign:'center',border:`3px solid ${i===4?COLOR.git.feature:COLOR.stroke.strong}`}}><div style={{...TYPE.title,fontFamily:FONT.mono,fontWeight:WEIGHT.bold}}>{x}</div></div>)}</div>;
// @git-course-scene hook:start
const Hook=()=>{const f=useCurrentFrame();return <AbsoluteFill><EpisodeTitleCard index="20." keyword="改一句说明" suffix="Hash 也变？" opacity={1} underlineScale={ap(f,.4)} auditId="ep20-hook"/><NarrationSubtitle frame={f} cues={R.captions('hook')} width={1320} bottom={64}/></AbsoluteFill>};
// @git-course-scene hook:end
// @git-course-scene amend:start
const Amend=()=> <Term scene="amend" id="ep20-amend" d={10} model={<><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>Amend 创建新对象，再移动 HEAD</SceneTitle><div style={{display:'flex',alignItems:'center',justifyContent:'center',gap:70,marginTop:360}}>{['old HEAD','new HEAD'].map((x,i)=><div key={x} style={{padding:'44px 70px',borderRadius:26,background:COLOR.canvas.raised,border:`4px solid ${i?COLOR.git.main:COLOR.text.tertiary}`,...TYPE.title,fontWeight:WEIGHT.bold}}>{x}</div>)}</div></>}/>;
// @git-course-scene amend:end
// @git-course-scene identity-change:start
const IdentityChange=()=>{const f=useCurrentFrame();return <AbsoluteFill><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>Hash 是对象内容的结果</SceneTitle><ObjectFields/><NarrationSubtitle frame={f} cues={R.captions('identity-change')} width={1320} bottom={64}/></AbsoluteFill>};
// @git-course-scene identity-change:end
// @git-course-scene interactive-todo:start
const InteractiveTodo=()=> <Term scene="interactive-todo" id="ep20-rebase" d={12} model={<div style={{padding:'130px 240px'}}><SceneTitle>Todo 先声明怎样重建</SceneTitle><div style={{marginTop:95,padding:44,borderRadius:24,background:COLOR.canvas.raised,fontFamily:FONT.mono,...TYPE.title,lineHeight:1.8}}><div>pick C1 draft</div><div style={{color:COLOR.git.main}}>reword C2 draft</div><div style={{color:COLOR.git.feature}}>squash C3 draft</div></div></div>}/>;
// @git-course-scene interactive-todo:end
// @git-course-scene rewrite-result:start
const RewriteResult=()=> <Term scene="rewrite-result" id="ep20-log" d={10} model={<div style={{padding:'130px 220px'}}><SceneTitle>后继 Parent 改变，身份链连续重建</SceneTitle><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:60,marginTop:100}}>{[['旧','C1 → C2 → C3'],['新','N1 → N2']].map((x,i)=><div key={x[0]} style={{padding:46,borderRadius:26,background:COLOR.canvas.raised,border:`3px solid ${i?COLOR.git.main:COLOR.text.tertiary}`}}><div style={{...TYPE.label,color:COLOR.text.tertiary}}>{x[0]}</div><div style={{...TYPE.hero,fontFamily:FONT.mono,fontWeight:WEIGHT.bold,marginTop:28}}>{x[1]}</div></div>)}</div></div>}/>;
// @git-course-scene rewrite-result:end
// @git-course-scene published-boundary:start
const PublishedBoundary=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{padding:'130px 230px'}}><SceneTitle>能重建，不等于应该重建</SceneTitle><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:48,marginTop:110}}>{[['LOCAL DRAFT','可先整理再发布',COLOR.git.main],['SHARED HISTORY','先评估协作成本',COLOR.git.conflict]].map((x,i)=><div key={x[0]} style={{padding:50,borderRadius:26,background:COLOR.canvas.raised,border:`4px solid ${x[2]}`,opacity:ap(f,2+i*4)}}><div style={{...TYPE.label,color:x[2]}}>{x[0]}</div><div style={{...TYPE.title,fontWeight:WEIGHT.bold,marginTop:30}}>{x[1]}</div></div>)}</div><NarrationSubtitle frame={f} cues={R.captions('published-boundary')} width={1320} bottom={64}/></AbsoluteFill>};
// @git-course-scene published-boundary:end
// @git-course-scene takeaway:start
const Takeaway=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{padding:'130px 220px'}}><SceneTitle>所谓改写，是新对象与新引用入口</SceneTitle><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:34,marginTop:110}}>{[['amend','最近一次'],['rebase -i','一段序列'],['shared?','先停下来']].map((x,i)=><div key={x[0]} style={{padding:42,borderRadius:24,background:COLOR.canvas.raised,textAlign:'center',opacity:ap(f,2+i*3)}}><div style={{...TYPE.title,fontFamily:FONT.mono,fontWeight:WEIGHT.bold}}>{x[0]}</div><div style={{...TYPE.body,marginTop:24}}>{x[1]}</div></div>)}</div><NarrationSubtitle frame={f} cues={R.captions('takeaway')} width={1320} bottom={64}/></AbsoluteFill>};
// @git-course-scene takeaway:end
const C={hook:Hook,amend:Amend,'identity-change':IdentityChange,'interactive-todo':InteractiveTodo,'rewrite-result':RewriteResult,'published-boundary':PublishedBoundary,takeaway:Takeaway}; export const Ep20RewritingHistory=()=>{const f=useCurrentFrame();return <CourseLayout seriesTitle={EP20.seriesTitle} episodeTitle={EP20.title} scenes={EP20_SCENES} currentFrame={f} showHeader={x=>x>=R.start('amend')} showEpisodeTitle={x=>x>=R.start('amend')}><EpisodeTimeline runtime={R} components={C}/></CourseLayout>};
