import {AbsoluteFill,interpolate,useCurrentFrame} from 'remotion';
import {EP22} from '../data/episodes';
import {EP22_DURATION_IN_FRAMES,EP22_SCENES} from '../data/episodeTimelines.generated';
import {TERMINAL_RECORDINGS} from '../data/terminalRecordings.generated';
import {CourseLayout,EpisodeTitleCard,EpisodeTimeline,NarrationSubtitle,RecordedTerminalCueSequence,SceneTitle,createEpisodeRuntime} from '../kit';
import {COLOR,FONT,WEIGHT} from '../palette'; import {seconds} from '../timeline'; import {TYPE} from '../typography';
export {EP22_DURATION_IN_FRAMES,EP22_SCENES};
const R=createEpisodeRuntime(EP22_SCENES); const appear=(f:number,a:number)=>interpolate(f,[seconds(a),seconds(a+.7)],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}); const cue=(id:keyof typeof TERMINAL_RECORDINGS,d:number)=>({id,from:0,durationInFrames:seconds(d+.7),src:`git-course-lab/terminal/${id}.mp4`,holdFrameSrc:`git-course-lab/terminal/${id}-hold.png`,holdFromFrame:TERMINAL_RECORDINGS[id].holdFromFrame});
const Term:React.FC<{scene:string;id:keyof typeof TERMINAL_RECORDINGS;d:number;result:React.ReactNode}>=({scene,id,d,result})=>{const f=useCurrentFrame();return <AbsoluteFill><RecordedTerminalCueSequence cues={[cue(id,d)]} rect={{x:250,y:132,width:1420,height:720}} auditIdPrefix={`ep22-${scene}-terminal`}/><AbsoluteFill style={{background:COLOR.canvas.base,opacity:appear(f,d)}}>{result}</AbsoluteFill><NarrationSubtitle frame={f} cues={R.captions(scene as never)} width={1320} bottom={64}/></AbsoluteFill>};
const CodeCard=()=> <div style={{width:1320,margin:'300px auto 0',padding:'42px 54px',borderRadius:26,background:COLOR.canvas.raised,fontFamily:FONT.mono,...TYPE.title,lineHeight:1.75}}><div>1 · export function retry(task) {'{'}</div><div>2 · &nbsp;&nbsp;const limit = 3</div><div style={{background:COLOR.effects.headHighlight,borderRadius:12,padding:'0 16px',margin:'4px -16px'}}>3 · &nbsp;&nbsp;return run(task, limit)</div><div>4 · {'}'}</div></div>;
// @git-course-scene hook:start
const Hook=()=>{const f=useCurrentFrame();return <AbsoluteFill><EpisodeTitleCard index="22." keyword="这一行" suffix="从哪来？" opacity={1} underlineScale={appear(f,.4)} auditId="ep22-hook"/><NarrationSubtitle frame={f} cues={R.captions('hook')} width={1320} bottom={64}/></AbsoluteFill>};
// @git-course-scene hook:end
// @git-course-scene line-entry:start
const LineEntry=()=>{const f=useCurrentFrame();return <AbsoluteFill><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>先从已知的文件与行号进入</SceneTitle><CodeCard/><NarrationSubtitle frame={f} cues={R.captions('line-entry')} width={1320} bottom={64}/></AbsoluteFill>};
// @git-course-scene line-entry:end
// @git-course-scene blame-range:start
const BlameRange=()=> <Term scene="blame-range" id="ep22-blame" d={11} result={<><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>Blame 给出最后一次修改线索</SceneTitle><div style={{display:'flex',justifyContent:'center',gap:42,marginTop:360}}>{['commit','author','time','line'].map((x,i)=><div key={x} style={{padding:'38px 52px',background:COLOR.canvas.raised,borderRadius:22,border:`4px solid ${i===0?COLOR.git.main:COLOR.stroke.strong}`,...TYPE.title,fontFamily:FONT.mono,fontWeight:WEIGHT.bold}}>{x}</div>)}</div></>}/>;
// @git-course-scene blame-range:end
// @git-course-scene open-commit:start
const OpenCommit=()=> <Term scene="open-commit" id="ep22-show" d={11} result={<><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>再回到提交、补丁与 Parent</SceneTitle><div style={{display:'flex',alignItems:'center',justifyContent:'center',gap:70,marginTop:370}}>{['blame 线索','git show','修改动机'].map((x,i)=><div key={x} style={{padding:'40px 60px',borderRadius:24,background:COLOR.canvas.raised,border:`4px solid ${i===1?COLOR.git.main:COLOR.stroke.strong}`,...TYPE.title,fontWeight:WEIGHT.bold}}>{x}</div>)}</div></>}/>;
// @git-course-scene open-commit:end
// @git-course-scene last-touch:start
const LastTouch=()=>{const f=useCurrentFrame();return <AbsoluteFill><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>最后触碰，不一定是最初设计</SceneTitle><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:56,width:1420,margin:'330px auto 0'}}>{[['SEMANTIC CHANGE','引入业务逻辑',COLOR.git.main],['LAST TOUCH','格式化或移动',COLOR.git.conflict]].map(([a,b,c],i)=><div key={a} style={{padding:48,borderRadius:26,background:COLOR.canvas.raised,border:`4px solid ${c}`,opacity:appear(f,1+i*3)}}><div style={{...TYPE.label,color:c}}>{a}</div><div style={{...TYPE.title,fontWeight:WEIGHT.bold,marginTop:28}}>{b}</div></div>)}</div><NarrationSubtitle frame={f} cues={R.captions('last-touch')} width={1320} bottom={64}/></AbsoluteFill>};
// @git-course-scene last-touch:end
// @git-course-scene heuristics:start
const Heuristics=()=> <Term scene="heuristics" id="ep22-heuristics" d={11} result={<><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>先去噪，再尝试追踪移动与复制</SceneTitle><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:36,width:1420,margin:'330px auto 0'}}>{[['-w','忽略空白'],['-M','追踪移动'],['-C','追踪复制']].map(([a,b])=><div key={a} style={{padding:42,borderRadius:24,background:COLOR.canvas.raised,textAlign:'center'}}><div style={{...TYPE.hero,fontFamily:FONT.mono,fontWeight:WEIGHT.bold,color:COLOR.git.main}}>{a}</div><div style={{...TYPE.body,marginTop:22}}>{b}</div></div>)}</div></>}/>;
// @git-course-scene heuristics:end
// @git-course-scene takeaway:start
const Takeaway=()=>{const f=useCurrentFrame();return <AbsoluteFill><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>Blame 是调查入口，不是责任判决</SceneTitle><div style={{display:'flex',alignItems:'center',justifyContent:'center',gap:42,marginTop:380}}>{['line','blame','show','context'].map((x,i)=><div key={x} style={{padding:'38px 48px',borderRadius:22,background:COLOR.canvas.raised,border:`4px solid ${i===3?COLOR.git.feature:COLOR.stroke.strong}`,...TYPE.title,fontFamily:FONT.mono,fontWeight:WEIGHT.bold,opacity:appear(f,1+i*2)}}>{x}</div>)}</div><NarrationSubtitle frame={f} cues={R.captions('takeaway')} width={1320} bottom={64}/></AbsoluteFill>};
// @git-course-scene takeaway:end
const C={hook:Hook,'line-entry':LineEntry,'blame-range':BlameRange,'open-commit':OpenCommit,'last-touch':LastTouch,heuristics:Heuristics,takeaway:Takeaway}; export const Ep22Blame=()=>{const f=useCurrentFrame();return <CourseLayout seriesTitle={EP22.seriesTitle} episodeTitle={EP22.title} scenes={EP22_SCENES} currentFrame={f} showHeader={x=>x>=R.start('line-entry')} showEpisodeTitle={x=>x>=R.start('line-entry')}><EpisodeTimeline runtime={R} components={C}/></CourseLayout>};
