import {AbsoluteFill,interpolate,useCurrentFrame} from 'remotion'; import {EP23} from '../data/episodes'; import {EP23_DURATION_IN_FRAMES,EP23_SCENES} from '../data/episodeTimelines.generated'; import {TERMINAL_RECORDINGS} from '../data/terminalRecordings.generated'; import {CenteredSceneBody,CourseLayout,EpisodeTitleCard,EpisodeTimeline,NarrationSubtitle,SceneTitle,TerminalThenModelScene,createEpisodeRuntime} from '../kit'; import {COLOR,FONT,WEIGHT} from '../palette'; import {seconds} from '../timeline'; import {TYPE} from '../typography';
export {EP23_DURATION_IN_FRAMES,EP23_SCENES}; const R=createEpisodeRuntime(EP23_SCENES); const appear=(f:number,a:number)=>interpolate(f,[seconds(a),seconds(a+.7)],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}); const cue=(id:keyof typeof TERMINAL_RECORDINGS,d:number)=>({id,from:0,durationInFrames:seconds(d+.7),src:`git-course-lab/terminal/${id}.mp4`,holdFrameSrc:`git-course-lab/terminal/${id}-hold.png`,holdFromFrame:TERMINAL_RECORDINGS[id].holdFromFrame});
const Term:React.FC<{scene:string;id:keyof typeof TERMINAL_RECORDINGS;d:number;result:React.ReactNode}>=({scene,id,d,result})=><TerminalThenModelScene cues={[cue(id,d)]} modelAtSeconds={d} model={result} captions={R.captions(scene as never)} auditIdPrefix={`ep23-${scene}-terminal`}/>;
const Interval:React.FC<{active?:number[]}>=({active=[0,1,2,3,4,5,6]})=> <CenteredSceneBody width={1054}><div style={{position:'relative',display:'flex',alignItems:'center',justifyContent:'center',gap:38}}><div style={{position:'absolute',left:59,right:59,top:57,height:5,background:COLOR.git.graphLine,zIndex:0}}/>{['G','C1','C2','C3','C4','C5','B'].map((x,i)=><div key={x} style={{position:'relative',zIndex:1,width:118,height:118,borderRadius:'50%',display:'grid',placeItems:'center',background:active.includes(i)?COLOR.canvas.raised:COLOR.canvas.soft,border:`5px solid ${i===0?COLOR.git.feature:i===6?COLOR.git.conflict:COLOR.git.main}`,opacity:active.includes(i)?1:.25,...TYPE.title,fontFamily:FONT.mono,fontWeight:WEIGHT.bold}}>{x}</div>)}</div></CenteredSceneBody>;
// @git-course-scene hook:start
const Hook=()=>{const f=useCurrentFrame();return <AbsoluteFill><EpisodeTitleCard index="23." keyword="测试失败" suffix="从哪开始？" opacity={1} underlineScale={appear(f,.4)} auditId="ep23-hook"/><NarrationSubtitle frame={f} cues={R.captions('hook')} width={1320} bottom={64}/></AbsoluteFill>};
// @git-course-scene hook:end
// @git-course-scene good-bad:start
const GoodBad=()=> <Term scene="good-bad" id="ep23-start" d={11} result={<><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>二分之前，先固定可信边界</SceneTitle><Interval/></>}/>;
// @git-course-scene good-bad:end
// @git-course-scene manual-rounds:start
const ManualRounds=()=> <Term scene="manual-rounds" id="ep23-manual" d={13} result={<><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>每一轮只回答：这个提交是 Good 还是 Bad？</SceneTitle><Interval active={[0,3,6]}/></>}/>;
// @git-course-scene manual-rounds:end
// @git-course-scene candidate-shrinks:start
const CandidateShrinks=()=>{const f=useCurrentFrame();const active=f<seconds(7)?[0,1,2,3,4,5,6]:f<seconds(14)?[3,4,5,6]:[4,5,6];return <AbsoluteFill><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>每次判断都缩小候选区间</SceneTitle><Interval active={active}/><NarrationSubtitle frame={f} cues={R.captions('candidate-shrinks')} width={1320} bottom={64}/></AbsoluteFill>};
// @git-course-scene candidate-shrinks:end
// @git-course-scene bisect-run:start
const BisectRun=()=> <Term scene="bisect-run" id="ep23-run" d={13} result={<><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>测试稳定时，让 bisect run 自动回答</SceneTitle><CenteredSceneBody width={1260} style={{padding:'46px',borderRadius:26,background:COLOR.canvas.raised,textAlign:'center'}}><div style={{...TYPE.hero,fontFamily:FONT.mono,fontWeight:WEIGHT.bold,color:COLOR.git.main}}>git bisect run ./test.sh</div></CenteredSceneBody></>}/>;
// @git-course-scene bisect-run:end
// @git-course-scene limits-reset:start
const LimitsReset=()=> <Term scene="limits-reset" id="ep23-reset" d={10} result={<><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>不稳定的测试会污染判断</SceneTitle><CenteredSceneBody width={1420} style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:36}}>{[['stable','可重复测试'],['skip','无法判断'],['reset','恢复起点']].map(([a,b],i)=><div key={a} style={{padding:42,borderRadius:24,background:COLOR.canvas.raised,textAlign:'center',border:`4px solid ${i===0?COLOR.git.feature:i===1?COLOR.git.conflict:COLOR.git.main}`}}><div style={{...TYPE.title,fontFamily:FONT.mono,fontWeight:WEIGHT.bold}}>{a}</div><div style={{...TYPE.body,marginTop:24}}>{b}</div></div>)}</CenteredSceneBody></>}/>;
// @git-course-scene limits-reset:end
// @git-course-scene takeaway:start
const Takeaway=()=>{const f=useCurrentFrame();return <AbsoluteFill><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>Bisect 把“逐个猜”变成边界搜索</SceneTitle><CenteredSceneBody width={1380} style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:42}}>{[['1','可信 Good / Bad'],['2','同一判定标准'],['3','结束后 reset']].map(([a,b],i)=><div key={a} style={{padding:44,borderRadius:24,background:COLOR.canvas.raised,textAlign:'center',opacity:appear(f,1+i*2)}}><div style={{...TYPE.hero,fontFamily:FONT.mono,fontWeight:WEIGHT.bold,color:COLOR.git.main}}>{a}</div><div style={{...TYPE.title,fontWeight:WEIGHT.bold,marginTop:22}}>{b}</div></div>)}</CenteredSceneBody><NarrationSubtitle frame={f} cues={R.captions('takeaway')} width={1320} bottom={64}/></AbsoluteFill>};
// @git-course-scene takeaway:end
const C={hook:Hook,'good-bad':GoodBad,'manual-rounds':ManualRounds,'candidate-shrinks':CandidateShrinks,'bisect-run':BisectRun,'limits-reset':LimitsReset,takeaway:Takeaway}; export const Ep23Bisect=()=>{const f=useCurrentFrame();return <CourseLayout seriesTitle={EP23.seriesTitle} episodeTitle={EP23.title} scenes={EP23_SCENES} currentFrame={f} showHeader={x=>x>=R.start('good-bad')} showEpisodeTitle={x=>x>=R.start('good-bad')}><EpisodeTimeline runtime={R} components={C}/></CourseLayout>};
