import {AbsoluteFill,interpolate,useCurrentFrame} from 'remotion'; import {EP24} from '../data/episodes'; import {EP24_DURATION_IN_FRAMES,EP24_SCENES} from '../data/episodeTimelines.generated'; import {TERMINAL_RECORDINGS} from '../data/terminalRecordings.generated'; import {CenteredSceneBody,CourseLayout,EpisodeTitleCard,EpisodeTimeline,GitStatePanel,NarrationSubtitle,SceneTitle,TerminalThenModelScene,createEpisodeRuntime} from '../kit'; import {COLOR,FONT,WEIGHT} from '../palette'; import {seconds} from '../timeline'; import {TYPE} from '../typography';
export {EP24_DURATION_IN_FRAMES,EP24_SCENES}; const R=createEpisodeRuntime(EP24_SCENES); const appear=(f:number,a:number)=>interpolate(f,[seconds(a),seconds(a+.7)],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}); const cue=(id:keyof typeof TERMINAL_RECORDINGS,d:number)=>({id,from:0,durationInFrames:seconds(d+.7),src:`git-course-lab/terminal/${id}.mp4`,holdFrameSrc:`git-course-lab/terminal/${id}-hold.png`,holdFromFrame:TERMINAL_RECORDINGS[id].holdFromFrame});
const Term:React.FC<{scene:string;id:keyof typeof TERMINAL_RECORDINGS;d:number;result:React.ReactNode}>=({scene,id,d,result})=><TerminalThenModelScene cues={[cue(id,d)]} modelAtSeconds={d} model={result} captions={R.captions(scene as never)} auditIdPrefix={`ep24-${scene}-terminal`}/>;
const ConflictState:React.FC<{resolved?:boolean;staged?:boolean}>=({resolved=false,staged=false})=> <CenteredSceneBody width={1450}><GitStatePanel areas={[{id:'working-tree',title:'Working Tree',files:[`app.js · ${resolved?'resolved':'unmerged'}`],active:true},{id:'index',title:'Index',files:[staged?'stage 0 · ready':'stage 1 / 2 / 3 · unmerged'],active:!staged},{id:'repository',title:'Rerere Cache',files:[resolved?'preimage + postimage':'waiting'],active:resolved}]}/></CenteredSceneBody>;
// @git-course-scene hook:start
const Hook=()=>{const f=useCurrentFrame();return <AbsoluteFill><EpisodeTitleCard index="24." keyword="同一冲突" suffix="还要重解？" opacity={1} underlineScale={appear(f,.4)} auditId="ep24-hook"/><NarrationSubtitle frame={f} cues={R.captions('hook')} width={1320} bottom={64}/></AbsoluteFill>};
// @git-course-scene hook:end
// @git-course-scene first-conflict:start
const FirstConflict=()=> <Term scene="first-conflict" id="ep24-first" d={11} result={<><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>第一次冲突，仍要真实判断</SceneTitle><ConflictState/></>}/>;
// @git-course-scene first-conflict:end
// @git-course-scene record-resolution:start
const RecordResolution=()=> <Term scene="record-resolution" id="ep24-resolve" d={11} result={<><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>Rerere 记录冲突形状与解决结果</SceneTitle><CenteredSceneBody width={1050} style={{display:'flex',alignItems:'center',justifyContent:'center',gap:70}}>{[['PREIMAGE','冲突形状'],['POSTIMAGE','解决结果']].map(([a,b],i)=><div key={a} style={{padding:'44px 76px',borderRadius:26,background:COLOR.canvas.raised,border:`4px solid ${i?COLOR.git.feature:COLOR.git.conflict}`,textAlign:'center'}}><div style={{...TYPE.label,color:i?COLOR.git.feature:COLOR.git.conflict}}>{a}</div><div style={{...TYPE.title,fontWeight:WEIGHT.bold,marginTop:24}}>{b}</div></div>)}</CenteredSceneBody></>}/>;
// @git-course-scene record-resolution:end
// @git-course-scene repeat-conflict:start
const RepeatConflict=()=> <Term scene="repeat-conflict" id="ep24-reuse" d={11} result={<><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>相同形状出现，复用已记录结果</SceneTitle><CenteredSceneBody width={1360} style={{padding:'46px 60px',borderRadius:26,background:COLOR.canvas.raised,textAlign:'center'}}><div style={{...TYPE.hero,fontFamily:FONT.mono,fontWeight:WEIGHT.bold,color:COLOR.git.feature}}>Resolved using previous resolution</div></CenteredSceneBody></>}/>;
// @git-course-scene repeat-conflict:end
// @git-course-scene reuse-working-tree:start
const ReuseWorkingTree=()=>{const f=useCurrentFrame();return <AbsoluteFill><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>复用先落在 Working Tree</SceneTitle><ConflictState resolved/><NarrationSubtitle frame={f} cues={R.captions('reuse-working-tree')} width={1320} bottom={64}/></AbsoluteFill>};
// @git-course-scene reuse-working-tree:end
// @git-course-scene verify-stage:start
const VerifyStage=()=> <Term scene="verify-stage" id="ep24-verify" d={10} result={<><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>检查、测试，再显式 git add</SceneTitle><ConflictState resolved staged/></>}/>;
// @git-course-scene verify-stage:end
// @git-course-scene takeaway:start
const Takeaway=()=>{const f=useCurrentFrame();return <AbsoluteFill><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>Rerere 复用判断，不替你做判断</SceneTitle><CenteredSceneBody width={1510} style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:30}}>{[['PREIMAGE','冲突'],['POSTIMAGE','结果'],['REUSE','写入 WT'],['VERIFY + ADD','确认暂存']].map(([a,b],i)=><div key={a} style={{padding:'38px 26px',borderRadius:24,background:COLOR.canvas.raised,textAlign:'center',opacity:appear(f,1+i*2)}}><div style={{...TYPE.label,color:i===0?COLOR.git.conflict:COLOR.git.main}}>{a}</div><div style={{...TYPE.title,fontWeight:WEIGHT.bold,marginTop:24}}>{b}</div></div>)}</CenteredSceneBody><NarrationSubtitle frame={f} cues={R.captions('takeaway')} width={1320} bottom={64}/></AbsoluteFill>};
// @git-course-scene takeaway:end
const C={hook:Hook,'first-conflict':FirstConflict,'record-resolution':RecordResolution,'repeat-conflict':RepeatConflict,'reuse-working-tree':ReuseWorkingTree,'verify-stage':VerifyStage,takeaway:Takeaway}; export const Ep24Rerere=()=>{const f=useCurrentFrame();return <CourseLayout seriesTitle={EP24.seriesTitle} episodeTitle={EP24.title} scenes={EP24_SCENES} currentFrame={f} showHeader={x=>x>=R.start('first-conflict')} showEpisodeTitle={x=>x>=R.start('first-conflict')}><EpisodeTimeline runtime={R} components={C}/></CourseLayout>};
