import {interpolate,useCurrentFrame} from 'remotion'; import {EP32} from '../data/episodes'; import {EP32_DURATION_IN_FRAMES,EP32_SCENES} from '../data/episodeTimelines.generated'; import {TERMINAL_RECORDINGS} from '../data/terminalRecordings.generated'; import {CenteredSceneBody,CourseBranchLabel,CourseCommitNode,CourseGraphEdge,CourseLayout,EpisodeTimeline,SceneTitle,TerminalThenModelScene,createEpisodeRuntime,courseCommitAnchor,courseCommitOuterRadius} from '../kit'; import {COLOR} from '../palette'; import {seconds} from '../timeline'; import {CompareCards,ModelScene,QuestionSceneVisual} from './WorkflowEpisodeVisuals';
export {EP32_DURATION_IN_FRAMES,EP32_SCENES}; const R=createEpisodeRuntime(EP32_SCENES); const cue=(id:string,d=10)=>({id:id as keyof typeof TERMINAL_RECORDINGS,from:0,durationInFrames:seconds(d+.7),src:`git-course-lab/terminal/${id}.mp4`,holdFrameSrc:`git-course-lab/terminal/${id}-hold.png`,holdFromFrame:TERMINAL_RECORDINGS[id as keyof typeof TERMINAL_RECORDINGS].holdFromFrame}); const Term=({scene,id,result,at=10}:{scene:Parameters<typeof R.captions>[0];id:string;result:React.ReactNode;at?:number})=><TerminalThenModelScene cues={[cue(id,at)]} modelAtSeconds={at} model={result} captions={R.captions(scene)} auditIdPrefix={`ep32-${scene}`}/>;
// @git-course-scene hook:start
const Hook=()=> <QuestionSceneVisual eyebrow="INTEGRATION STRATEGY" question="文件相同，历史也相同吗？" captions={R.captions('hook')}/>;
// @git-course-scene hook:end
// @git-course-scene same-start:start
const SameStartGraph=()=>{const frame=useCurrentFrame();const baseIn=interpolate(frame,[seconds(.4),seconds(.8)],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});const mainIn=interpolate(frame,[seconds(.8),seconds(1.2)],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});const topicIn=interpolate(frame,[seconds(1.15),seconds(1.65)],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});const p={base:{x:210,y:270},main:{x:650,y:150},c1:{x:650,y:390},c2:{x:1080,y:390}};const radius=courseCommitOuterRadius({size:'hero',strong:true});const anchor=(point:{x:number;y:number})=>courseCommitAnchor(point.x,point.y,{size:'hero',strong:true});return <CenteredSceneBody width={1420}><svg width="1420" height="540" viewBox="0 0 1420 540" style={{display:'block',overflow:'visible'}}><g data-graph-layer="edges"><CourseGraphEdge from={anchor(p.main)} to={anchor(p.base)} size="hero" opacity={mainIn}/><CourseGraphEdge from={anchor(p.c1)} to={anchor(p.base)} size="hero" opacity={topicIn}/><CourseGraphEdge from={anchor(p.c2)} to={anchor(p.c1)} size="hero" opacity={topicIn}/></g><g data-graph-layer="refs"><CourseBranchLabel name="main" x={p.main.x} placement="above" targetX={p.main.x} targetY={p.main.y} targetRadius={radius} size="hero" color={COLOR.git.main} opacity={mainIn}/><CourseBranchLabel name="topic" x={p.c2.x} placement="below" targetX={p.c2.x} targetY={p.c2.y} targetRadius={radius} size="hero" color={COLOR.git.feature} opacity={topicIn}/></g><g data-graph-layer="nodes"><CourseCommitNode id="Base" {...p.base} size="hero" tone="base" opacity={baseIn}/><CourseCommitNode id="M1" {...p.main} size="hero" tone="main" opacity={mainIn}/><CourseCommitNode id="C1" {...p.c1} size="hero" tone="feature" opacity={topicIn}/><CourseCommitNode id="C2" {...p.c2} size="hero" tone="feature" opacity={topicIn}/></g></svg></CenteredSceneBody>};
const SameStart=()=> <ModelScene title="同一 Base，分出 Main 与 Topic" captions={R.captions('same-start')}><SameStartGraph/></ModelScene>;
// @git-course-scene same-start:end
// @git-course-scene merge-path:start
const MergePath=()=> <Term scene="merge-path" id="ep32-merge-path" at={11} result={<><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>Merge 保留拓扑与原 Commit 身份</SceneTitle><CompareCards cards={[{label:'Parents',detail:'main + topic'},{label:'Topic OIDs',detail:'保持不变',tone:'feature'},{label:'Topology',detail:'保留分叉',tone:'head'}]}/></>}/>;
// @git-course-scene merge-path:end
// @git-course-scene rebase-path:start
const RebasePath=()=> <Term scene="rebase-path" id="ep32-rebase-path" result={<><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>Rebase 在新 Base 上重建 Commit</SceneTitle><CompareCards cards={[{label:'Linear',detail:'目标可 fast-forward'},{label:'New OIDs',detail:'parent 改变',tone:'feature'},{label:'Shared?',detail:'已共享时谨慎',tone:'head'}]}/></>}/>;
// @git-course-scene rebase-path:end
// @git-course-scene pick-path:start
const PickPath=()=> <Term scene="pick-path" id="ep32-pick-path" result={<><SceneTitle style={{position:'absolute',top:112,left:180,right:180}}>Cherry-pick 只接收选中的变化</SceneTitle><CompareCards cards={[{label:'Selected',detail:'指定 commit',tone:'feature'},{label:'New OIDs',detail:'目标上新建',tone:'head'},{label:'No ancestry',detail:'来源 topic 不成为祖先'}]}/></>}/>;
// @git-course-scene pick-path:end
// @git-course-scene takeaway:start
const Takeaway=()=> <ModelScene title="先回答四个问题，再选命令" captions={R.captions('takeaway')}><CompareCards cards={[{label:'Topology',detail:'保留分叉吗'},{label:'Identity',detail:'保留原 commit 吗',tone:'feature'},{label:'Range',detail:'全部还是部分',tone:'head'},{label:'Shared',detail:'branch 已共享吗',tone:'conflict'}]}/></ModelScene>;
// @git-course-scene takeaway:end
const C={hook:Hook,'same-start':SameStart,'merge-path':MergePath,'rebase-path':RebasePath,'pick-path':PickPath,takeaway:Takeaway}; export const Ep32ChoosingIntegrationStrategy=()=>{const f=useCurrentFrame();return <CourseLayout seriesTitle={EP32.seriesTitle} episodeTitle={EP32.title} scenes={EP32_SCENES} currentFrame={f} showHeader={x=>x>=R.start('same-start')} showEpisodeTitle={x=>x>=R.start('same-start')}><EpisodeTimeline runtime={R} components={C}/></CourseLayout>};
